//  Generated by desperion protocol_builder

#ifndef core_guild_in_alliance_versatile_informations_hpp
#define core_guild_in_alliance_versatile_informations_hpp

namespace protocol
{
    struct guild_in_alliance_versatile_informations : guild_versatile_informations
    {
        int32_t alliance_id;
        
        int16_t id() const override
        { return 437; } 
        
        guild_in_alliance_versatile_informations(const int32_t & guild_id, const int32_t & leader_id, const int16_t & guild_level, const int16_t & nb_members, const int32_t & alliance_id) : guild_versatile_informations { guild_id,leader_id,guild_level,nb_members }
        {
            _data << alliance_id;
        }
        
        guild_in_alliance_versatile_informations(byte_buffer & data) : guild_versatile_informations { data }
        {
            data >> alliance_id;
        }
    };
    
    using guild_in_alliance_versatile_informations_ptr = std::unique_ptr<guild_in_alliance_versatile_informations>;
}

#endif
