//  Generated by desperion protocol_builder

#ifndef core_game_role_play_free_soul_request_message_hpp
#define core_game_role_play_free_soul_request_message_hpp

namespace network
{
    struct game_role_play_free_soul_request_message : dofus_unit
    {
        
        int16_t id() const override
        { return 745; } 
        
        game_role_play_free_soul_request_message()
        {
        }
        
        game_role_play_free_soul_request_message(byte_buffer & data)
        {
        }
    };
}

#endif
