//  Generated by desperion protocol_builder

#ifndef d2fstream_optional_feature_hpp
#define d2fstream_optional_feature_hpp

namespace datacenter
{
    struct optional_feature : data_holder
    {
        int32_t id;
        std::string keyword;
        
        optional_feature() = default;
        
        optional_feature(const int32_t & id, const std::string & keyword) : id { id }, keyword { keyword }
        {
        }
        
        optional_feature(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(keyword, data.second.at("keyword"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<optional_feature>();
        release(id, data.second["id"], file);
        release(keyword, data.second["keyword"], file);
        return data;
    }
#endif
}
#endif