//  Generated by desperion protocol_builder

#ifndef core_character_deletion_error_enum_hpp
#define core_character_deletion_error_enum_hpp

namespace protocol
{
    enum character_deletion_error
    {
        DEL_ERR_NO_REASON = 1,
        DEL_ERR_TOO_MANY_CHAR_DELETION = 2,
        DEL_ERR_BAD_SECRET_ANSWER = 3,
        DEL_ERR_RESTRICED_ZONE = 4,
    };
}

#endif
