//  Generated by desperion protocol_builder

#ifndef core_compass_type_enum_hpp
#define core_compass_type_enum_hpp

namespace network
{
    enum compass_type
    {
        COMPASS_TYPE_SIMPLE = 0,
        COMPASS_TYPE_SPOUSE = 1,
        COMPASS_TYPE_PARTY = 2,
        COMPASS_TYPE_PVP_SEEK = 3,
        COMPASS_TYPE_QUEST = 4,
    };
}

#endif
