//  Generated by desperion protocol_builder

#ifndef core_console_message_type_enum_hpp
#define core_console_message_type_enum_hpp

namespace network
{
    enum console_message_type
    {
        CONSOLE_TEXT_MESSAGE = 0,
        CONSOLE_INFO_MESSAGE = 1,
        CONSOLE_ERR_MESSAGE = 2,
    };
}

#endif
