//  Generated by desperion protocol_builder

#ifndef core_crafter_directory_param_bit_enum_hpp
#define core_crafter_directory_param_bit_enum_hpp

namespace protocol
{
    enum crafter_directory_param_bit
    {
        CRAFT_OPTION_NONE = 0,
        CRAFT_OPTION_NOT_FREE = 1,
        CRAFT_OPTION_NOT_FREE_EXCEPT_ON_FAIL = 2,
        CRAFT_OPTION_RESOURCES_REQUIRED = 4,
    };
}

#endif
