//  Generated by desperion protocol_builder

#ifndef core_debug_level_enum_hpp
#define core_debug_level_enum_hpp

namespace protocol
{
    enum debug_level
    {
        LEVEL_TRACE = 0,
        LEVEL_DEBUG = 1,
        LEVEL_INFO = 2,
        LEVEL_WARN = 3,
        LEVEL_ERROR = 4,
        LEVEL_FATAL = 5,
    };
}

#endif
