//  Generated by desperion protocol_builder

#ifndef core_delayed_action_type_enum_hpp
#define core_delayed_action_type_enum_hpp

namespace protocol
{
    enum delayed_action_type
    {
        DELAYED_ACTION_DISCONNECT = 0,
        DELAYED_ACTION_OBJECT_USE = 1,
        DELAYED_ACTION_JOIN_CHARACTER = 2,
        DELAYED_ACTION_AGGRESSION_IMMUNE = 3,
    };
}

#endif
