//  Generated by desperion protocol_builder

#ifndef core_directions_enum_hpp
#define core_directions_enum_hpp

namespace network
{
    enum directions
    {
        DIRECTION_EAST = 0,
        DIRECTION_SOUTH_EAST = 1,
        DIRECTION_SOUTH = 2,
        DIRECTION_SOUTH_WEST = 3,
        DIRECTION_WEST = 4,
        DIRECTION_NORTH_WEST = 5,
        DIRECTION_NORTH = 6,
        DIRECTION_NORTH_EAST = 7,
    };
}

#endif
