//  Generated by desperion protocol_builder

#ifndef core_exchange_error_enum_hpp
#define core_exchange_error_enum_hpp

namespace protocol
{
    enum exchange_error
    {
        REQUEST_IMPOSSIBLE = 1,
        REQUEST_CHARACTER_OCCUPIED = 2,
        REQUEST_CHARACTER_JOB_NOT_EQUIPED = 3,
        REQUEST_CHARACTER_TOOL_TOO_FAR = 4,
        REQUEST_CHARACTER_OVERLOADED = 5,
        REQUEST_CHARACTER_NOT_SUSCRIBER = 6,
        REQUEST_CHARACTER_RESTRICTED = 7,
        BUY_ERROR = 8,
        SELL_ERROR = 9,
        MOUNT_PADDOCK_ERROR = 10,
        BID_SEARCH_ERROR = 11,
    };
}

#endif
