//  Generated by desperion protocol_builder

#ifndef core_fight_options_enum_hpp
#define core_fight_options_enum_hpp

namespace protocol
{
    enum fight_options
    {
        FIGHT_OPTION_SET_SECRET = 0,
        FIGHT_OPTION_SET_TO_PARTY_ONLY = 1,
        FIGHT_OPTION_SET_CLOSED = 2,
        FIGHT_OPTION_ASK_FOR_HELP = 3,
    };
}

#endif
