//  Generated by desperion protocol_builder

#ifndef core_fight_dispellable_enum_hpp
#define core_fight_dispellable_enum_hpp

namespace protocol
{
    enum fight_dispellable
    {
        DISPELLABLE = 1,
        DISPELLABLE_BY_DEATH = 2,
        DISPELLABLE_BY_STRONG_DISPEL = 3,
        REALLY_NOT_DISPELLABLE = 4,
    };
}

#endif
