//  Generated by desperion protocol_builder

#ifndef core_fight_spell_cast_critical_enum_hpp
#define core_fight_spell_cast_critical_enum_hpp

namespace network
{
    enum fight_spell_cast_critical
    {
        NORMAL = 1,
        CRITICAL_HIT = 2,
        CRITICAL_FAIL = 3,
    };
}

#endif
