//  Generated by desperion protocol_builder

#ifndef core_game_context_enum_hpp
#define core_game_context_enum_hpp

namespace network
{
    enum game_context
    {
        ROLE_PLAY = 1,
        FIGHT = 2,
    };
}

#endif
