//  Generated by desperion protocol_builder

#ifndef core_list_add_failure_enum_hpp
#define core_list_add_failure_enum_hpp

namespace protocol
{
    enum list_add_failure
    {
        LIST_ADD_FAILURE_UNKNOWN = 0,
        LIST_ADD_FAILURE_OVER_QUOTA = 1,
        LIST_ADD_FAILURE_NOT_FOUND = 2,
        LIST_ADD_FAILURE_EGOCENTRIC = 3,
        LIST_ADD_FAILURE_IS_DOUBLE = 4,
    };
}

#endif
