//  Generated by desperion protocol_builder

#ifndef core_nickname_error_enum_hpp
#define core_nickname_error_enum_hpp

namespace protocol
{
    enum nickname_error
    {
        ALREADY_USED = 1,
        SAME_AS_LOGIN = 2,
        TOO_SIMILAR_TO_LOGIN = 3,
        INVALID_NICK = 4,
        UNKNOWN_NICK_ERROR = 99,
    };
}

#endif
