//  Generated by desperion protocol_builder

#ifndef core_payment_type_enum_hpp
#define core_payment_type_enum_hpp

namespace network
{
    enum payment_type
    {
        PAYMENT_ON_SUCCESS_ONLY = 0,
        PAYMENT_IN_ANY_CASE = 1,
    };
}

#endif
