//  Generated by desperion protocol_builder

#ifndef core_player_status_enum_hpp
#define core_player_status_enum_hpp

namespace network
{
    enum player_status
    {
        PLAYER_STATUS_OFFLINE = 0,
        PLAYER_STATUS_UNKNOWN = 1,
        PLAYER_STATUS_AVAILABLE = 10,
        PLAYER_STATUS_IDLE = 20,
        PLAYER_STATUS_AFK = 21,
        PLAYER_STATUS_PRIVATE = 30,
        PLAYER_STATUS_SOLO = 40,
    };
}

#endif
