//  Generated by desperion protocol_builder

#ifndef core_preset_save_update_error_enum_hpp
#define core_preset_save_update_error_enum_hpp

namespace protocol
{
    enum preset_save_update_error
    {
        PRESET_UPDATE_ERR_UNKNOWN = 1,
        PRESET_UPDATE_ERR_BAD_PRESET_ID = 2,
        PRESET_UPDATE_ERR_BAD_POSITION = 3,
        PRESET_UPDATE_ERR_BAD_OBJECT_ID = 4,
    };
}

#endif
