//  Generated by desperion protocol_builder

#ifndef core_pvp_arena_step_enum_hpp
#define core_pvp_arena_step_enum_hpp

namespace protocol
{
    enum pvp_arena_step
    {
        ARENA_STEP_REGISTRED = 0,
        ARENA_STEP_WAITING_FIGHT = 1,
        ARENA_STEP_STARTING_FIGHT = 2,
        ARENA_STEP_UNREGISTER = 3,
    };
}

#endif
