//  Generated by desperion protocol_builder

#ifndef core_social_contact_category_enum_hpp
#define core_social_contact_category_enum_hpp

namespace network
{
    enum social_contact_category
    {
        SOCIAL_CONTACT_FRIEND = 0,
        SOCIAL_CONTACT_SPOUSE = 1,
        SOCIAL_CONTACT_PARTY = 2,
        SOCIAL_CONTACT_GUILD = 3,
        SOCIAL_CONTACT_ALLIANCE = 4,
        SOCIAL_CONTACT_CRAFTER = 5,
        SOCIAL_CONTACT_INTERLOCUTOR = 6,
    };
}

#endif
