//  Generated by desperion protocol_builder

#ifndef core_teleporter_type_enum_hpp
#define core_teleporter_type_enum_hpp

namespace protocol
{
    enum teleporter_type
    {
        TELEPORTER_ZAAP = 0,
        TELEPORTER_SUBWAY = 1,
        TELEPORTER_PRISM = 2,
    };
}

#endif
