//  Generated by desperion protocol_builder

#ifndef core_updatable_mount_boost_enum_hpp
#define core_updatable_mount_boost_enum_hpp

namespace protocol
{
    enum updatable_mount_boost
    {
        STAMINA = 3,
        MATURITY = 5,
        ENERGY = 1,
        SERENITY = 2,
        LOVE = 4,
        TIREDNESS = 6,
    };
}

#endif
