//  Generated by desperion protocol_builder

#ifndef core_compass_reset_message_hpp
#define core_compass_reset_message_hpp

namespace network
{
    struct compass_reset_message : dofus_unit
    {
        int8_t type;
        
        int16_t id() const override
        { return 5584; } 
        
        compass_reset_message(const int8_t & type)
        {
            _data << type;
        }
        
        compass_reset_message(byte_buffer & data)
        {
            data >> type;
        }
    };
}

#endif
