//  Generated by desperion protocol_builder

#ifndef core_inventory_preset_item_update_request_message_hpp
#define core_inventory_preset_item_update_request_message_hpp

namespace network
{
    struct inventory_preset_item_update_request_message : dofus_unit
    {
        int8_t preset_id;
        int8_t position;
        int32_t obj_uid;
        
        int16_t id() const override
        { return 6210; } 
        
        inventory_preset_item_update_request_message(const int8_t & preset_id, const int8_t & position, const int32_t & obj_uid)
        {
            _data << preset_id;
            _data << position;
            _data << obj_uid;
        }
        
        inventory_preset_item_update_request_message(byte_buffer & data)
        {
            data >> preset_id;
            data >> position;
            data >> obj_uid;
        }
    };
}

#endif
