//  Generated by desperion protocol_builder

#ifndef core_object_average_prices_get_message_hpp
#define core_object_average_prices_get_message_hpp

namespace network
{
    struct object_average_prices_get_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6334; } 
        
        object_average_prices_get_message()
        {
        }
        
        object_average_prices_get_message(byte_buffer & data)
        {
        }
    };
}

#endif
