//  Generated by desperion protocol_builder

#ifndef d2fstream_server_community_hpp
#define d2fstream_server_community_hpp

namespace datacenter
{
    struct server_community : data_holder
    {
        int32_t id;
        int32_t name_id;
        std::string short_id;
        std::vector<std::string> default_countries;
        
        server_community() = default;
        
        server_community(const int32_t & id, const int32_t & name_id, const std::string & short_id, const std::vector<std::string> & default_countries) : id { id }, name_id { name_id }, short_id { short_id }, default_countries { default_countries }
        {
        }
        
        server_community(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(name_id, data.second.at("nameId"));
            acquire(short_id, data.second.at("shortId"));
            acquire(default_countries, data.second.at("defaultCountries"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<server_community>();
        release(id, data.second["id"], file);
        release(name_id, data.second["nameId"], file);
        release(short_id, data.second["shortId"], file);
        release(default_countries, data.second["defaultCountries"], file);
        return data;
    }
#endif
}
#endif