//  Generated by desperion protocol_builder

#ifndef core_friends_get_list_message_hpp
#define core_friends_get_list_message_hpp

namespace network
{
    struct friends_get_list_message : dofus_unit
    {
        
        int16_t id() const override
        { return 4001; } 
        
        friends_get_list_message()
        {
        }
        
        friends_get_list_message(byte_buffer & data)
        {
        }
    };
}

#endif
