//  Generated by desperion protocol_builder

#ifndef core_ignored_add_failure_message_hpp
#define core_ignored_add_failure_message_hpp

namespace protocol
{
    struct ignored_add_failure_message : dofus_unit
    {
        int8_t reason;
        
        int16_t id() const override
        { return 5679; } 
        
        ignored_add_failure_message(const int8_t & reason)
        {
            _data << reason;
        }
        
        ignored_add_failure_message(byte_buffer & data)
        {
            data >> reason;
        }
    };
}

#endif
