//  Generated by desperion protocol_builder

#ifndef core_ignored_delete_request_message_hpp
#define core_ignored_delete_request_message_hpp

namespace network
{
    struct ignored_delete_request_message : dofus_unit
    {
        int32_t account_id;
        bool session;
        
        int16_t id() const override
        { return 5680; } 
        
        ignored_delete_request_message(const int32_t & account_id, const bool & session)
        {
            _data << account_id;
            _data << session;
        }
        
        ignored_delete_request_message(byte_buffer & data)
        {
            data >> account_id;
            data >> session;
        }
    };
}

#endif
