//  Generated by desperion protocol_builder

#ifndef core_ignored_list_message_hpp
#define core_ignored_list_message_hpp

namespace protocol
{
    struct ignored_list_message : dofus_unit
    {
        std::vector<ignored_informations_ptr> ignored_list;
        
        int16_t id() const override
        { return 5674; } 
        
        ignored_list_message(const std::vector<ignored_informations_ptr> & ignored_list)
        {
            _data << static_cast<int16_t>(ignored_list.size());
            for (auto && i : ignored_list)
                _data << i->id() << i->buffer();
        }
        
        ignored_list_message(byte_buffer & data)
        {
            int16_t ignored_list_size;
            data >> ignored_list_size;
            ignored_list.resize(ignored_list_size);
            for (int16_t i = 0; i < ignored_list_size; ++i)
            {
                int16_t p;
                data >> p;
                ignored_list[i].reset(type_manager::get_ignored_informations(p, data));
            }
        }
    };
}

#endif
