//  Generated by desperion protocol_builder

#ifndef core_spouse_get_informations_message_hpp
#define core_spouse_get_informations_message_hpp

namespace network
{
    struct spouse_get_informations_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6355; } 
        
        spouse_get_informations_message()
        {
        }
        
        spouse_get_informations_message(byte_buffer & data)
        {
        }
    };
}

#endif
