//  Generated by desperion protocol_builder

#ifndef core_game_role_play_delayed_action_message_hpp
#define core_game_role_play_delayed_action_message_hpp

namespace protocol
{
    struct game_role_play_delayed_action_message : dofus_unit
    {
        int32_t delayed_character_id;
        int8_t delay_type_id;
        double delay_end_time;
        
        int16_t id() const override
        { return 6153; } 
        
        game_role_play_delayed_action_message(const int32_t & delayed_character_id, const int8_t & delay_type_id, const double & delay_end_time)
        {
            _data << delayed_character_id;
            _data << delay_type_id;
            _data << delay_end_time;
        }
        
        game_role_play_delayed_action_message(byte_buffer & data)
        {
            data >> delayed_character_id;
            data >> delay_type_id;
            data >> delay_end_time;
        }
    };
}

#endif
