//  Generated by desperion protocol_builder

#ifndef core_acquaintance_server_list_message_hpp
#define core_acquaintance_server_list_message_hpp

namespace protocol
{
    struct acquaintance_server_list_message : dofus_unit
    {
        std::vector<int16_t> servers;
        
        int16_t id() const override
        { return 6142; }

        acquaintance_server_list_message(const std::set<int16_t> & servers)
        {
            _data << static_cast<int16_t>(servers.size());
            for (auto && i : servers)
                _data << i;
        }
        
        acquaintance_server_list_message(const std::vector<int16_t> & servers)
        {
            _data << static_cast<int16_t>(servers.size());
            for (auto && i : servers)
                _data << i;
        }
        
        acquaintance_server_list_message(byte_buffer & data)
        {
            int16_t servers_size;
            data >> servers_size;
            servers.resize(servers_size);
            for (int16_t i = 0; i < servers_size; ++i)
                data >> servers[i];
        }
    };
}

#endif
