//  Generated by desperion protocol_builder

#ifndef core_parts_list_message_hpp
#define core_parts_list_message_hpp

namespace network
{
    struct parts_list_message : dofus_unit
    {
        std::vector<content_part_ptr> parts;
        
        int16_t id() const override
        { return 1502; } 
        
        parts_list_message(const std::vector<content_part_ptr> & parts)
        {
            _data << static_cast<int16_t>(parts.size());
            for (auto && i : parts)
                _data << i->buffer();
        }
        
        parts_list_message(byte_buffer & data)
        {
            int16_t parts_size;
            data >> parts_size;
            parts.resize(parts_size);
            for (int16_t i = 0; i < parts_size; ++i)
                parts[i] = std::make_unique<content_part>(data);
        }
    };
}

#endif
