//  Generated by desperion protocol_builder

#ifndef core_contact_look_message_hpp
#define core_contact_look_message_hpp

namespace protocol
{
    struct contact_look_message : dofus_unit
    {
        int32_t request_id;
        std::string player_name;
        int32_t player_id;
        entity_look_ptr look;
        
        int16_t id() const override
        { return 5934; } 
        
        contact_look_message(const int32_t & request_id, const std::string & player_name, const int32_t & player_id, const entity_look_ptr & look)
        {
            _data << request_id;
            _data << player_name;
            _data << player_id;
            _data << look->buffer();
        }
        
        contact_look_message(byte_buffer & data)
        {
            data >> request_id;
            data >> player_name;
            data >> player_id;
            look = std::make_unique<entity_look>(data);
        }
    };
}

#endif
