//  Generated by desperion protocol_builder

#ifndef core_contact_look_error_message_hpp
#define core_contact_look_error_message_hpp

namespace protocol
{
    struct contact_look_error_message : dofus_unit
    {
        int32_t request_id;
        
        int16_t id() const override
        { return 6045; } 
        
        contact_look_error_message(const int32_t & request_id)
        {
            _data << request_id;
        }
        
        contact_look_error_message(byte_buffer & data)
        {
            data >> request_id;
        }
    };
}

#endif
