//  Generated by desperion protocol_builder

#ifndef core_contact_look_request_by_id_message_hpp
#define core_contact_look_request_by_id_message_hpp

namespace network
{
    struct contact_look_request_by_id_message : contact_look_request_message
    {
        int32_t player_id;
        
        int16_t id() const override
        { return 5935; } 
        
        contact_look_request_by_id_message(const int8_t & request_id, const int8_t & contact_type, const int32_t & player_id) : contact_look_request_message { request_id,contact_type }
        {
            _data << player_id;
        }
        
        contact_look_request_by_id_message(byte_buffer & data) : contact_look_request_message { data }
        {
            data >> player_id;
        }
    };
}

#endif
