//  Generated by desperion protocol_builder

#ifndef core_challenge_dungeon_stacked_bonus_message_hpp
#define core_challenge_dungeon_stacked_bonus_message_hpp

namespace protocol
{
    struct challenge_dungeon_stacked_bonus_message : dofus_unit
    {
        int32_t dungeon_id;
        int32_t xp_bonus;
        int32_t drop_bonus;
        
        int16_t id() const override
        { return 6151; } 
        
        challenge_dungeon_stacked_bonus_message(const int32_t & dungeon_id, const int32_t & xp_bonus, const int32_t & drop_bonus)
        {
            _data << dungeon_id;
            _data << xp_bonus;
            _data << drop_bonus;
        }
        
        challenge_dungeon_stacked_bonus_message(byte_buffer & data)
        {
            data >> dungeon_id;
            data >> xp_bonus;
            data >> drop_bonus;
        }
    };
}

#endif
