//  Generated by desperion protocol_builder

#ifndef core_inventory_preset_item_update_error_message_hpp
#define core_inventory_preset_item_update_error_message_hpp

namespace protocol
{
    struct inventory_preset_item_update_error_message : dofus_unit
    {
        int8_t code;
        
        int16_t id() const override
        { return 6211; } 
        
        inventory_preset_item_update_error_message(const int8_t & code)
        {
            _data << code;
        }
        
        inventory_preset_item_update_error_message(byte_buffer & data)
        {
            data >> code;
        }
    };
}

#endif
