//  Generated by desperion protocol_builder

#ifndef core_inventory_preset_save_custom_message_hpp
#define core_inventory_preset_save_custom_message_hpp

namespace protocol
{
    struct inventory_preset_save_custom_message : dofus_unit
    {
        int8_t preset_id;
        int8_t symbol_id;
        std::vector<int8_t> items_positions;
        std::vector<int32_t> items_uids;
        
        int16_t id() const override
        { return 6329; } 
        
        inventory_preset_save_custom_message(const int8_t & preset_id, const int8_t & symbol_id, const std::vector<int8_t> & items_positions, const std::vector<int32_t> & items_uids)
        {
            _data << preset_id;
            _data << symbol_id;
            _data << items_positions;
            _data << static_cast<int16_t>(items_uids.size());
            for (auto && i : items_uids)
                _data << i;
        }
        
        inventory_preset_save_custom_message(byte_buffer & data)
        {
            data >> preset_id;
            data >> symbol_id;
            data >> items_positions;
            int16_t items_uids_size;
            data >> items_uids_size;
            items_uids.resize(items_uids_size);
            for (int16_t i = 0; i < items_uids_size; ++i)
                data >> items_uids[i];
        }
    };
}

#endif
