//  Generated by desperion protocol_builder

#ifndef core_pause_dialog_message_hpp
#define core_pause_dialog_message_hpp

namespace network
{
    struct pause_dialog_message : dofus_unit
    {
        int8_t dialog_type;
        
        int16_t id() const override
        { return 6012; } 
        
        pause_dialog_message(const int8_t & dialog_type)
        {
            _data << dialog_type;
        }
        
        pause_dialog_message(byte_buffer & data)
        {
            data >> dialog_type;
        }
    };
}

#endif
