//  Generated by desperion protocol_builder

#ifndef core_zaap_list_message_hpp
#define core_zaap_list_message_hpp

namespace protocol
{
    struct zaap_list_message : teleport_destinations_list_message
    {
        int32_t spawn_map_id;
        
        int16_t id() const override
        { return 1604; } 
        
        zaap_list_message(const int8_t & teleporter_type, const std::vector<int32_t> & map_ids, const std::vector<int16_t> & sub_area_ids, const std::vector<int16_t> & costs, const int32_t & spawn_map_id) : teleport_destinations_list_message { teleporter_type,map_ids,sub_area_ids,costs }
        {
            _data << spawn_map_id;
        }
        
        zaap_list_message(byte_buffer & data) : teleport_destinations_list_message { data }
        {
            data >> spawn_map_id;
        }
    };
}

#endif
