//  Generated by desperion protocol_builder

#ifndef core_fight_options_informations_hpp
#define core_fight_options_informations_hpp

namespace protocol
{
    struct fight_options_informations : dofus_unit
    {
        bool is_secret;
        bool is_restricted_to_party_only;
        bool is_closed;
        bool is_asking_for_help;
        
        int16_t id() const override
        { return 20; } 
        
        fight_options_informations(const bool & is_secret, const bool & is_restricted_to_party_only, const bool & is_closed, const bool & is_asking_for_help)
        {
            int8_t flag = 0;
            set_bool_flag(flag, 0, is_secret);
            set_bool_flag(flag, 1, is_restricted_to_party_only);
            set_bool_flag(flag, 2, is_closed);
            set_bool_flag(flag, 3, is_asking_for_help);
            _data << flag;
        }
        
        fight_options_informations(byte_buffer & data)
        {
            int8_t flag;
            data >> flag;
            is_secret = get_bool_flag(flag, 0);
            is_restricted_to_party_only = get_bool_flag(flag, 1);
            is_closed = get_bool_flag(flag, 2);
            is_asking_for_help = get_bool_flag(flag, 3);
        }
    };
    
    using fight_options_informations_ptr = std::unique_ptr<fight_options_informations>;
}

#endif
