//  Generated by desperion protocol_builder

#ifndef core_fight_team_member_tax_collector_informations_hpp
#define core_fight_team_member_tax_collector_informations_hpp

namespace protocol
{
    struct fight_team_member_tax_collector_informations : fight_team_member_informations
    {
        int16_t first_name_id;
        int16_t last_name_id;
        int8_t level;
        int32_t guild_id;
        int32_t uid;
        
        int16_t id() const override
        { return 177; } 
        
        fight_team_member_tax_collector_informations(const int32_t & id, const int16_t & first_name_id, const int16_t & last_name_id, const int8_t & level, const int32_t & guild_id, const int32_t & uid) : fight_team_member_informations { id }
        {
            _data << first_name_id;
            _data << last_name_id;
            _data << level;
            _data << guild_id;
            _data << uid;
        }
        
        fight_team_member_tax_collector_informations(byte_buffer & data) : fight_team_member_informations { data }
        {
            data >> first_name_id;
            data >> last_name_id;
            data >> level;
            data >> guild_id;
            data >> uid;
        }
    };
    
    using fight_team_member_tax_collector_informations_ptr = std::unique_ptr<fight_team_member_tax_collector_informations>;
}

#endif
