//  Generated by desperion protocol_builder

#ifndef core_fight_team_member_character_informations_hpp
#define core_fight_team_member_character_informations_hpp

namespace network
{
    struct fight_team_member_character_informations : fight_team_member_informations
    {
        std::string name;
        int16_t level;
        
        int16_t id() const override
        { return 13; } 
        
        fight_team_member_character_informations(const int32_t & id, const std::string & name, const int16_t & level) : fight_team_member_informations { id }
        {
            _data << name;
            _data << level;
        }
        
        fight_team_member_character_informations(byte_buffer & data) : fight_team_member_informations { data }
        {
            data >> name;
            data >> level;
        }
    };
    
    using fight_team_member_character_informations_ptr = std::unique_ptr<fight_team_member_character_informations>;
}

#endif
