//  Generated by desperion protocol_builder

#ifndef core_fight_alliance_team_informations_hpp
#define core_fight_alliance_team_informations_hpp

namespace protocol
{
    struct fight_alliance_team_informations : fight_team_informations
    {
        int8_t relation;
        
        int16_t id() const override
        { return 439; } 
        
        fight_alliance_team_informations(const std::vector<fight_team_member_informations_ptr> & team_members, const int8_t & team_id, const int32_t & leader_id, const int8_t & team_side, const int8_t & team_type_id, const int8_t & relation) : fight_team_informations { team_members,team_id,leader_id,team_side,team_type_id }
        {
            _data << relation;
        }
        
        fight_alliance_team_informations(byte_buffer & data) : fight_team_informations { data }
        {
            data >> relation;
        }
    };
    
    using fight_alliance_team_informations_ptr = std::unique_ptr<fight_alliance_team_informations>;
}

#endif
