//  Generated by desperion protocol_builder

#ifndef core_guild_kick_request_message_hpp
#define core_guild_kick_request_message_hpp

namespace protocol
{
    struct guild_kick_request_message : dofus_unit
    {
        int32_t kicked_id;
        
        int16_t id() const override
        { return 5887; } 
        
        guild_kick_request_message(const int32_t & kicked_id)
        {
            _data << kicked_id;
        }
        
        guild_kick_request_message(byte_buffer & data)
        {
            data >> kicked_id;
        }
    };
}

#endif
