//  Generated by desperion protocol_builder

#ifndef core_guild_creation_started_message_hpp
#define core_guild_creation_started_message_hpp

namespace protocol
{
    struct guild_creation_started_message : dofus_unit
    {
        
        int16_t id() const override
        { return 5920; } 
        
        guild_creation_started_message()
        {
        }
        
        guild_creation_started_message(byte_buffer & data)
        {
        }
    };
}

#endif
