//  Generated by desperion protocol_builder

#ifndef core_guild_invitation_message_hpp
#define core_guild_invitation_message_hpp

namespace network
{
    struct guild_invitation_message : dofus_unit
    {
        int32_t target_id;
        
        int16_t id() const override
        { return 5551; } 
        
        guild_invitation_message(const int32_t & target_id)
        {
            _data << target_id;
        }
        
        guild_invitation_message(byte_buffer & data)
        {
            data >> target_id;
        }
    };
}

#endif
