//  Generated by desperion protocol_builder

#ifndef core_guild_change_member_parameters_message_hpp
#define core_guild_change_member_parameters_message_hpp

namespace network
{
    struct guild_change_member_parameters_message : dofus_unit
    {
        int32_t member_id;
        int16_t rank;
        int8_t experience_given_percent;
        unsigned_int_ptr rights;
        
        int16_t id() const override
        { return 5549; } 
        
        guild_change_member_parameters_message(const int32_t & member_id, const int16_t & rank, const int8_t & experience_given_percent, const unsigned_int_ptr & rights)
        {
            _data << member_id;
            _data << rank;
            _data << experience_given_percent;
            _data << rights->buffer();
        }
        
        guild_change_member_parameters_message(byte_buffer & data)
        {
            data >> member_id;
            data >> rank;
            data >> experience_given_percent;
            rights = std::make_unique<unsigned_int>(data);
        }
    };
}

#endif
