//  Generated by desperion protocol_builder

#ifndef core_mount_rename_request_message_hpp
#define core_mount_rename_request_message_hpp

namespace protocol
{
    struct mount_rename_request_message : dofus_unit
    {
        std::string name;
        double mount_id;
        
        int16_t id() const override
        { return 5987; } 
        
        mount_rename_request_message(const std::string & name, const double & mount_id)
        {
            _data << name;
            _data << mount_id;
        }
        
        mount_rename_request_message(byte_buffer & data)
        {
            data >> name;
            data >> mount_id;
        }
    };
}

#endif
