//  Generated by desperion protocol_builder

#ifndef core_mount_un_set_message_hpp
#define core_mount_un_set_message_hpp

namespace network
{
    struct mount_un_set_message : dofus_unit
    {
        
        int16_t id() const override
        { return 5982; } 
        
        mount_un_set_message()
        {
        }
        
        mount_un_set_message(byte_buffer & data)
        {
        }
    };
}

#endif
