//  Generated by desperion protocol_builder

#ifndef core_mount_information_in_paddock_request_message_hpp
#define core_mount_information_in_paddock_request_message_hpp

namespace network
{
    struct mount_information_in_paddock_request_message : dofus_unit
    {
        int32_t map_ride_id;
        
        int16_t id() const override
        { return 5975; } 
        
        mount_information_in_paddock_request_message(const int32_t & map_ride_id)
        {
            _data << map_ride_id;
        }
        
        mount_information_in_paddock_request_message(byte_buffer & data)
        {
            data >> map_ride_id;
        }
    };
}

#endif
