//  Generated by desperion protocol_builder

#ifndef core_mount_equiped_error_message_hpp
#define core_mount_equiped_error_message_hpp

namespace protocol
{
    struct mount_equiped_error_message : dofus_unit
    {
        int8_t error_type;
        
        int16_t id() const override
        { return 5963; } 
        
        mount_equiped_error_message(const int8_t & error_type)
        {
            _data << error_type;
        }
        
        mount_equiped_error_message(byte_buffer & data)
        {
            data >> error_type;
        }
    };
}

#endif
