//  Generated by desperion protocol_builder

#ifndef core_mount_set_xp_ratio_request_message_hpp
#define core_mount_set_xp_ratio_request_message_hpp

namespace protocol
{
    struct mount_set_xp_ratio_request_message : dofus_unit
    {
        int8_t xp_ratio;
        
        int16_t id() const override
        { return 5989; } 
        
        mount_set_xp_ratio_request_message(const int8_t & xp_ratio)
        {
            _data << xp_ratio;
        }
        
        mount_set_xp_ratio_request_message(byte_buffer & data)
        {
            data >> xp_ratio;
        }
    };
}

#endif
