//  Generated by desperion protocol_builder

#ifndef core_subscription_zone_message_hpp
#define core_subscription_zone_message_hpp

namespace network
{
    struct subscription_zone_message : dofus_unit
    {
        bool active;
        
        int16_t id() const override
        { return 5573; } 
        
        subscription_zone_message(const bool & active)
        {
            _data << active;
        }
        
        subscription_zone_message(byte_buffer & data)
        {
            data >> active;
        }
    };
}

#endif
