//  Generated by desperion protocol_builder

#ifndef core_basic_who_is_request_message_hpp
#define core_basic_who_is_request_message_hpp

namespace protocol
{
    struct basic_who_is_request_message : dofus_unit
    {
        bool verbose;
        std::string search;
        
        int16_t id() const override
        { return 181; } 
        
        basic_who_is_request_message(const bool & verbose, const std::string & search)
        {
            _data << verbose;
            _data << search;
        }
        
        basic_who_is_request_message(byte_buffer & data)
        {
            data >> verbose;
            data >> search;
        }
    };
}

#endif
