//  Generated by desperion protocol_builder

#ifndef core_basic_ack_message_hpp
#define core_basic_ack_message_hpp

namespace protocol
{
    struct basic_ack_message : dofus_unit
    {
        int32_t seq;
        int16_t last_packet_id;
        
        int16_t id() const override
        { return 6362; } 
        
        basic_ack_message(const int32_t & seq, const int16_t & last_packet_id)
        {
            _data << seq;
            _data << last_packet_id;
        }
        
        basic_ack_message(byte_buffer & data)
        {
            data >> seq;
            data >> last_packet_id;
        }
    };
}

#endif
