//  Generated by desperion protocol_builder

#ifndef core_numeric_who_is_request_message_hpp
#define core_numeric_who_is_request_message_hpp

namespace network
{
    struct numeric_who_is_request_message : dofus_unit
    {
        int32_t player_id;
        
        int16_t id() const override
        { return 6298; } 
        
        numeric_who_is_request_message(const int32_t & player_id)
        {
            _data << player_id;
        }
        
        numeric_who_is_request_message(byte_buffer & data)
        {
            data >> player_id;
        }
    };
}

#endif
