//  Generated by desperion protocol_builder

#ifndef core_dungeon_party_finder_available_dungeons_request_message_hpp
#define core_dungeon_party_finder_available_dungeons_request_message_hpp

namespace network
{
    struct dungeon_party_finder_available_dungeons_request_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6240; } 
        
        dungeon_party_finder_available_dungeons_request_message()
        {
        }
        
        dungeon_party_finder_available_dungeons_request_message(byte_buffer & data)
        {
        }
    };
}

#endif
