//  Generated by desperion protocol_builder

#ifndef core_dungeon_party_finder_room_content_update_message_hpp
#define core_dungeon_party_finder_room_content_update_message_hpp

namespace protocol
{
    struct dungeon_party_finder_room_content_update_message : dofus_unit
    {
        int16_t dungeon_id;
        std::vector<dungeon_party_finder_player_ptr> added_players;
        std::vector<int32_t> removed_players_ids;
        
        int16_t id() const override
        { return 6250; } 
        
        dungeon_party_finder_room_content_update_message(const int16_t & dungeon_id, const std::vector<dungeon_party_finder_player_ptr> & added_players, const std::vector<int32_t> & removed_players_ids)
        {
            _data << dungeon_id;
            _data << static_cast<int16_t>(added_players.size());
            for (auto && i : added_players)
                _data << i->buffer();
            _data << static_cast<int16_t>(removed_players_ids.size());
            for (auto && i : removed_players_ids)
                _data << i;
        }
        
        dungeon_party_finder_room_content_update_message(byte_buffer & data)
        {
            data >> dungeon_id;
            int16_t added_players_size;
            data >> added_players_size;
            added_players.resize(added_players_size);
            for (int16_t i = 0; i < added_players_size; ++i)
                added_players[i] = std::make_unique<dungeon_party_finder_player>(data);
            int16_t removed_players_ids_size;
            data >> removed_players_ids_size;
            removed_players_ids.resize(removed_players_ids_size);
            for (int16_t i = 0; i < removed_players_ids_size; ++i)
                data >> removed_players_ids[i];
        }
    };
}

#endif
