//  Generated by desperion protocol_builder

#ifndef core_dungeon_party_finder_register_request_message_hpp
#define core_dungeon_party_finder_register_request_message_hpp

namespace network
{
    struct dungeon_party_finder_register_request_message : dofus_unit
    {
        std::vector<int16_t> dungeon_ids;
        
        int16_t id() const override
        { return 6249; } 
        
        dungeon_party_finder_register_request_message(const std::vector<int16_t> & dungeon_ids)
        {
            _data << static_cast<int16_t>(dungeon_ids.size());
            for (auto && i : dungeon_ids)
                _data << i;
        }
        
        dungeon_party_finder_register_request_message(byte_buffer & data)
        {
            int16_t dungeon_ids_size;
            data >> dungeon_ids_size;
            dungeon_ids.resize(dungeon_ids_size);
            for (int16_t i = 0; i < dungeon_ids_size; ++i)
                data >> dungeon_ids[i];
        }
    };
}

#endif
