//  Generated by desperion protocol_builder

#ifndef core_party_invitation_request_message_hpp
#define core_party_invitation_request_message_hpp

namespace protocol
{
    struct party_invitation_request_message : dofus_unit
    {
        std::string name;
        
        int16_t id() const override
        { return 5585; } 
        
        party_invitation_request_message(const std::string & name)
        {
            _data << name;
        }
        
        party_invitation_request_message(byte_buffer & data)
        {
            data >> name;
        }
    };
}

#endif
