//  Generated by desperion protocol_builder

#ifndef core_party_new_guest_message_hpp
#define core_party_new_guest_message_hpp

namespace protocol
{
    struct party_new_guest_message : abstract_party_event_message
    {
        party_guest_informations_ptr guest;
        
        int16_t id() const override
        { return 6260; } 
        
        party_new_guest_message(const int32_t & party_id, const party_guest_informations_ptr & guest) : abstract_party_event_message { party_id }
        {
            _data << guest->buffer();
        }
        
        party_new_guest_message(byte_buffer & data) : abstract_party_event_message { data }
        {
            guest = std::make_unique<party_guest_informations>(data);
        }
    };
}

#endif
