//  Generated by desperion protocol_builder

#ifndef core_party_leave_message_hpp
#define core_party_leave_message_hpp

namespace protocol
{
    struct party_leave_message : abstract_party_message
    {
        
        int16_t id() const override
        { return 5594; } 
        
        party_leave_message(const int32_t & party_id) : abstract_party_message { party_id }
        {
        }
        
        party_leave_message(byte_buffer & data) : abstract_party_message { data }
        {
        }
    };
}

#endif
