//  Generated by desperion protocol_builder

#ifndef core_party_cancel_invitation_message_hpp
#define core_party_cancel_invitation_message_hpp

namespace protocol
{
    struct party_cancel_invitation_message : abstract_party_message
    {
        int32_t guest_id;
        
        int16_t id() const override
        { return 6254; } 
        
        party_cancel_invitation_message(const int32_t & party_id, const int32_t & guest_id) : abstract_party_message { party_id }
        {
            _data << guest_id;
        }
        
        party_cancel_invitation_message(byte_buffer & data) : abstract_party_message { data }
        {
            data >> guest_id;
        }
    };
}

#endif
