//  Generated by desperion protocol_builder

#ifndef core_party_modifiable_status_message_hpp
#define core_party_modifiable_status_message_hpp

namespace protocol
{
    struct party_modifiable_status_message : abstract_party_message
    {
        bool enabled;
        
        int16_t id() const override
        { return 6277; } 
        
        party_modifiable_status_message(const int32_t & party_id, const bool & enabled) : abstract_party_message { party_id }
        {
            _data << enabled;
        }
        
        party_modifiable_status_message(byte_buffer & data) : abstract_party_message { data }
        {
            data >> enabled;
        }
    };
}

#endif
