//  Generated by desperion protocol_builder

#ifndef core_hello_connect_message_hpp
#define core_hello_connect_message_hpp

namespace protocol
{
    struct hello_connect_message : dofus_unit
    {
        std::string salt;
        std::vector<int8_t> key;
        
        int16_t id() const override
        { return 3; } 
        
        hello_connect_message(const std::string & salt, const std::vector<int8_t> & key)
        {
            _data << salt;
            _data << key;
        }
        
        hello_connect_message(byte_buffer & data)
        {
            data >> salt;
            data >> key;
        }
    };
}

#endif
