//  Generated by desperion protocol_builder

#ifndef core_selected_server_data_message_hpp
#define core_selected_server_data_message_hpp

namespace protocol
{
    struct selected_server_data_message : dofus_unit
    {
        int16_t server_id;
        std::string address;
        int16_t port;
        bool can_create_new_character;
        std::string ticket;
        
        int16_t id() const override
        { return 42; } 
        
        selected_server_data_message(const int16_t & server_id, const std::string & address, const int16_t & port, const bool & can_create_new_character, const std::string & ticket)
        {
            _data << server_id;
            _data << address;
            _data << port;
            _data << can_create_new_character;
            _data << ticket;
        }
        
        selected_server_data_message(byte_buffer & data)
        {
            data >> server_id;
            data >> address;
            data >> port;
            data >> can_create_new_character;
            data >> ticket;
        }
    };
}

#endif
