//  Generated by desperion protocol_builder

#ifndef core_server_selection_message_hpp
#define core_server_selection_message_hpp

namespace protocol
{
    struct server_selection_message : dofus_unit
    {
        int16_t server_id;
        
        int16_t id() const override
        { return 40; } 
        
        server_selection_message(const int16_t & server_id)
        {
            _data << server_id;
        }
        
        server_selection_message(byte_buffer & data)
        {
            data >> server_id;
        }
    };
}

#endif
