//  Generated by desperion protocol_builder

#ifndef core_server_status_update_message_hpp
#define core_server_status_update_message_hpp

namespace protocol
{
    struct server_status_update_message : dofus_unit
    {
        game_server_informations_ptr server;
        
        int16_t id() const override
        { return 50; } 
        
        server_status_update_message(const game_server_informations_ptr & server)
        {
            _data << server->buffer();
        }
        
        server_status_update_message(byte_buffer & data)
        {
            server = std::make_unique<game_server_informations>(data);
        }
    };
}

#endif
