//  Generated by desperion protocol_builder

#ifndef core_game_fight_starting_message_hpp
#define core_game_fight_starting_message_hpp

namespace protocol
{
    struct game_fight_starting_message : dofus_unit
    {
        int8_t fight_type;
        
        int16_t id() const override
        { return 700; } 
        
        game_fight_starting_message(const int8_t & fight_type)
        {
            _data << fight_type;
        }
        
        game_fight_starting_message(byte_buffer & data)
        {
            data >> fight_type;
        }
    };
}

#endif
