//  Generated by desperion protocol_builder

#ifndef core_game_fight_turn_list_message_hpp
#define core_game_fight_turn_list_message_hpp

namespace network
{
    struct game_fight_turn_list_message : dofus_unit
    {
        std::vector<int32_t> ids;
        std::vector<int32_t> deads_ids;
        
        int16_t id() const override
        { return 713; } 
        
        game_fight_turn_list_message(const std::vector<int32_t> & ids, const std::vector<int32_t> & deads_ids)
        {
            _data << static_cast<int16_t>(ids.size());
            for (auto && i : ids)
                _data << i;
            _data << static_cast<int16_t>(deads_ids.size());
            for (auto && i : deads_ids)
                _data << i;
        }
        
        game_fight_turn_list_message(byte_buffer & data)
        {
            int16_t ids_size;
            data >> ids_size;
            ids.resize(ids_size);
            for (int16_t i = 0; i < ids_size; ++i)
                data >> ids[i];
            int16_t deads_ids_size;
            data >> deads_ids_size;
            deads_ids.resize(deads_ids_size);
            for (int16_t i = 0; i < deads_ids_size; ++i)
                data >> deads_ids[i];
        }
    };
}

#endif
