//  Generated by desperion protocol_builder

#ifndef core_game_fight_human_ready_state_message_hpp
#define core_game_fight_human_ready_state_message_hpp

namespace protocol
{
    struct game_fight_human_ready_state_message : dofus_unit
    {
        int32_t character_id;
        bool is_ready;
        
        int16_t id() const override
        { return 740; } 
        
        game_fight_human_ready_state_message(const int32_t & character_id, const bool & is_ready)
        {
            _data << character_id;
            _data << is_ready;
        }
        
        game_fight_human_ready_state_message(byte_buffer & data)
        {
            data >> character_id;
            data >> is_ready;
        }
    };
}

#endif
