//  Generated by desperion protocol_builder

#ifndef core_game_fight_update_team_message_hpp
#define core_game_fight_update_team_message_hpp

namespace protocol
{
    struct game_fight_update_team_message : dofus_unit
    {
        int16_t fight_id;
        fight_team_informations_ptr team;
        
        int16_t id() const override
        { return 5572; } 
        
        game_fight_update_team_message(const int16_t & fight_id, const fight_team_informations_ptr & team)
        {
            _data << fight_id;
            _data << team->buffer();
        }
        
        game_fight_update_team_message(byte_buffer & data)
        {
            data >> fight_id;
            team = std::make_unique<fight_team_informations>(data);
        }
    };
}

#endif
