//  Generated by desperion protocol_builder

#ifndef core_game_fight_turn_start_message_hpp
#define core_game_fight_turn_start_message_hpp

namespace protocol
{
    struct game_fight_turn_start_message : dofus_unit
    {
        int32_t id;
        int32_t wait_time;
        
        int16_t id() const override
        { return 714; } 
        
        game_fight_turn_start_message(const int32_t & id, const int32_t & wait_time)
        {
            _data << id;
            _data << wait_time;
        }
        
        game_fight_turn_start_message(byte_buffer & data)
        {
            data >> id;
            data >> wait_time;
        }
    };
}

#endif
