//  Generated by desperion protocol_builder

#ifndef core_game_role_play_player_fight_friendly_answered_message_hpp
#define core_game_role_play_player_fight_friendly_answered_message_hpp

namespace network
{
    struct game_role_play_player_fight_friendly_answered_message : dofus_unit
    {
        int32_t fight_id;
        int32_t source_id;
        int32_t target_id;
        bool accept;
        
        int16_t id() const override
        { return 5733; } 
        
        game_role_play_player_fight_friendly_answered_message(const int32_t & fight_id, const int32_t & source_id, const int32_t & target_id, const bool & accept)
        {
            _data << fight_id;
            _data << source_id;
            _data << target_id;
            _data << accept;
        }
        
        game_role_play_player_fight_friendly_answered_message(byte_buffer & data)
        {
            data >> fight_id;
            data >> source_id;
            data >> target_id;
            data >> accept;
        }
    };
}

#endif
