//  Generated by desperion protocol_builder

#ifndef d2fstream_super_area_hpp
#define d2fstream_super_area_hpp

namespace datacenter
{
    struct super_area : data_holder
    {
        int32_t id;
        int32_t name_id;
        int32_t worldmap_id;
        
        super_area() = default;
        
        super_area(const int32_t & id, const int32_t & name_id, const int32_t & worldmap_id) : id { id }, name_id { name_id }, worldmap_id { worldmap_id }
        {
        }
        
        super_area(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(name_id, data.second.at("nameId"));
            acquire(worldmap_id, data.second.at("worldmapId"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<super_area>();
        release(id, data.second["id"], file);
        release(name_id, data.second["nameId"], file);
        release(worldmap_id, data.second["worldmapId"], file);
        return data;
    }
#endif
}
#endif