//  Generated by desperion protocol_builder

#ifndef core_guild_fact_sheet_informations_hpp
#define core_guild_fact_sheet_informations_hpp

namespace network
{
    struct guild_fact_sheet_informations : guild_informations
    {
        int32_t leader_id;
        int8_t guild_level;
        int16_t nb_members;
        
        int16_t id() const override
        { return 424; } 
        
        guild_fact_sheet_informations(const guild_emblem_ptr & guild_emblem, const int32_t & guild_id, const std::string & guild_name, const int32_t & leader_id, const int8_t & guild_level, const int16_t & nb_members) : guild_informations { guild_emblem,guild_id,guild_name }
        {
            _data << leader_id;
            _data << guild_level;
            _data << nb_members;
        }
        
        guild_fact_sheet_informations(byte_buffer & data) : guild_informations { data }
        {
            data >> leader_id;
            data >> guild_level;
            data >> nb_members;
        }
    };
    
    using guild_fact_sheet_informations_ptr = std::unique_ptr<guild_fact_sheet_informations>;
}

#endif
