//  Generated by desperion protocol_builder

#ifndef core_popup_warning_message_hpp
#define core_popup_warning_message_hpp

namespace network
{
    struct popup_warning_message : dofus_unit
    {
        int8_t lock_duration;
        std::string author;
        std::string content;
        
        int16_t id() const override
        { return 6134; } 
        
        popup_warning_message(const int8_t & lock_duration, const std::string & author, const std::string & content)
        {
            _data << lock_duration;
            _data << author;
            _data << content;
        }
        
        popup_warning_message(byte_buffer & data)
        {
            data >> lock_duration;
            data >> author;
            data >> content;
        }
    };
}

#endif
