//  Generated by desperion protocol_builder

#ifndef core_character_selection_with_relook_message_hpp
#define core_character_selection_with_relook_message_hpp

namespace network
{
    struct character_selection_with_relook_message : character_selection_message
    {
        int32_t cosmetic_id;
        
        int16_t id() const override
        { return 6353; } 
        
        character_selection_with_relook_message(const int32_t & id, const int32_t & cosmetic_id) : character_selection_message { id }
        {
            _data << cosmetic_id;
        }
        
        character_selection_with_relook_message(byte_buffer & data) : character_selection_message { data }
        {
            data >> cosmetic_id;
        }
    };
}

#endif
