//  Generated by desperion protocol_builder

#ifndef core_storage_objects_update_message_hpp
#define core_storage_objects_update_message_hpp

namespace protocol
{
    struct storage_objects_update_message : dofus_unit
    {
        std::vector<object_item_ptr> object_list;
        
        int16_t id() const override
        { return 6036; } 
        
        storage_objects_update_message(const std::vector<object_item_ptr> & object_list)
        {
            _data << static_cast<int16_t>(object_list.size());
            for (auto && i : object_list)
                _data << i->buffer();
        }
        
        storage_objects_update_message(byte_buffer & data)
        {
            int16_t object_list_size;
            data >> object_list_size;
            object_list.resize(object_list_size);
            for (int16_t i = 0; i < object_list_size; ++i)
                object_list[i] = std::make_unique<object_item>(data);
        }
    };
}

#endif
