//  Generated by desperion protocol_builder

#ifndef core_quest_step_validated_message_hpp
#define core_quest_step_validated_message_hpp

namespace protocol
{
    struct quest_step_validated_message : dofus_unit
    {
        int16_t quest_id;
        int16_t step_id;
        
        int16_t id() const override
        { return 6099; } 
        
        quest_step_validated_message(const int16_t & quest_id, const int16_t & step_id)
        {
            _data << quest_id;
            _data << step_id;
        }
        
        quest_step_validated_message(byte_buffer & data)
        {
            data >> quest_id;
            data >> step_id;
        }
    };
}

#endif
