//  Generated by desperion protocol_builder

#ifndef core_system_message_display_message_hpp
#define core_system_message_display_message_hpp

namespace protocol
{
    struct system_message_display_message : dofus_unit
    {
        bool hang_up;
        int16_t msg_id;
        std::vector<std::string> parameters;
        
        int16_t id() const override
        { return 189; } 
        
        system_message_display_message(const bool & hang_up, const int16_t & msg_id, const std::vector<std::string> & parameters)
        {
            _data << hang_up;
            _data << msg_id;
            _data << static_cast<int16_t>(parameters.size());
            for (auto && i : parameters)
                _data << i;
        }
        
        system_message_display_message(byte_buffer & data)
        {
            data >> hang_up;
            data >> msg_id;
            int16_t parameters_size;
            data >> parameters_size;
            parameters.resize(parameters_size);
            for (int16_t i = 0; i < parameters_size; ++i)
                data >> parameters[i];
        }
    };
}

#endif
