//  Generated by desperion protocol_builder

#ifndef core_teleport_to_buddy_offer_message_hpp
#define core_teleport_to_buddy_offer_message_hpp

namespace protocol
{
    struct teleport_to_buddy_offer_message : dofus_unit
    {
        int16_t dungeon_id;
        int32_t buddy_id;
        int32_t time_left;
        
        int16_t id() const override
        { return 6287; } 
        
        teleport_to_buddy_offer_message(const int16_t & dungeon_id, const int32_t & buddy_id, const int32_t & time_left)
        {
            _data << dungeon_id;
            _data << buddy_id;
            _data << time_left;
        }
        
        teleport_to_buddy_offer_message(byte_buffer & data)
        {
            data >> dungeon_id;
            data >> buddy_id;
            data >> time_left;
        }
    };
}

#endif
