//  Generated by desperion protocol_builder

#ifndef core_spell_upgrade_failure_message_hpp
#define core_spell_upgrade_failure_message_hpp

namespace protocol
{
    struct spell_upgrade_failure_message : dofus_unit
    {
        
        int16_t id() const override
        { return 1202; } 
        
        spell_upgrade_failure_message()
        {
        }
        
        spell_upgrade_failure_message(byte_buffer & data)
        {
        }
    };
}

#endif
