//  Generated by desperion protocol_builder

#ifndef core_quest_objective_informations_with_completion_hpp
#define core_quest_objective_informations_with_completion_hpp

namespace network
{
    struct quest_objective_informations_with_completion : quest_objective_informations
    {
        int16_t cur_completion;
        int16_t max_completion;
        
        int16_t id() const override
        { return 386; } 
        
        quest_objective_informations_with_completion(const int16_t & objective_id, const bool & objective_status, const std::vector<std::string> & dialog_params, const int16_t & cur_completion, const int16_t & max_completion) : quest_objective_informations { objective_id,objective_status,dialog_params }
        {
            _data << cur_completion;
            _data << max_completion;
        }
        
        quest_objective_informations_with_completion(byte_buffer & data) : quest_objective_informations { data }
        {
            data >> cur_completion;
            data >> max_completion;
        }
    };
    
    using quest_objective_informations_with_completion_ptr = std::unique_ptr<quest_objective_informations_with_completion>;
}

#endif
