//  Generated by desperion protocol_builder

#ifndef core_quest_active_informations_hpp
#define core_quest_active_informations_hpp

namespace network
{
    struct quest_active_informations : dofus_unit
    {
        int16_t quest_id;
        
        int16_t id() const override
        { return 381; } 
        
        quest_active_informations(const int16_t & quest_id)
        {
            _data << quest_id;
        }
        
        quest_active_informations(byte_buffer & data)
        {
            data >> quest_id;
        }
    };
    
    using quest_active_informations_ptr = std::unique_ptr<quest_active_informations>;
}

#endif
