//  Generated by desperion protocol_builder

#ifndef core_alliance_prism_dialog_question_message_hpp
#define core_alliance_prism_dialog_question_message_hpp

namespace network
{
    struct alliance_prism_dialog_question_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6448; } 
        
        alliance_prism_dialog_question_message()
        {
        }
        
        alliance_prism_dialog_question_message(byte_buffer & data)
        {
        }
    };
}

#endif
