//  Generated by desperion protocol_builder

#ifndef core_npc_dialog_question_message_hpp
#define core_npc_dialog_question_message_hpp

namespace network
{
    struct npc_dialog_question_message : dofus_unit
    {
        int16_t message_id;
        std::vector<std::string> dialog_params;
        std::vector<int16_t> visible_replies;
        
        int16_t id() const override
        { return 5617; } 
        
        npc_dialog_question_message(const int16_t & message_id, const std::vector<std::string> & dialog_params, const std::vector<int16_t> & visible_replies)
        {
            _data << message_id;
            _data << static_cast<int16_t>(dialog_params.size());
            for (auto && i : dialog_params)
                _data << i;
            _data << static_cast<int16_t>(visible_replies.size());
            for (auto && i : visible_replies)
                _data << i;
        }
        
        npc_dialog_question_message(byte_buffer & data)
        {
            data >> message_id;
            int16_t dialog_params_size;
            data >> dialog_params_size;
            dialog_params.resize(dialog_params_size);
            for (int16_t i = 0; i < dialog_params_size; ++i)
                data >> dialog_params[i];
            int16_t visible_replies_size;
            data >> visible_replies_size;
            visible_replies.resize(visible_replies_size);
            for (int16_t i = 0; i < visible_replies_size; ++i)
                data >> visible_replies[i];
        }
    };
}

#endif
