//  Generated by desperion protocol_builder

#ifndef core_npc_dialog_reply_message_hpp
#define core_npc_dialog_reply_message_hpp

namespace network
{
    struct npc_dialog_reply_message : dofus_unit
    {
        int16_t reply_id;
        
        int16_t id() const override
        { return 5616; } 
        
        npc_dialog_reply_message(const int16_t & reply_id)
        {
            _data << reply_id;
        }
        
        npc_dialog_reply_message(byte_buffer & data)
        {
            data >> reply_id;
        }
    };
}

#endif
