//  Generated by desperion protocol_builder

#ifndef core_house_informations_inside_hpp
#define core_house_informations_inside_hpp

namespace network
{
    struct house_informations_inside : dofus_unit
    {
        int32_t house_id;
        int16_t model_id;
        int32_t owner_id;
        std::string owner_name;
        int16_t world_x;
        int16_t world_y;
        unsigned_int_ptr price;
        bool is_locked;
        
        int16_t id() const override
        { return 218; } 
        
        house_informations_inside(const int32_t & house_id, const int16_t & model_id, const int32_t & owner_id, const std::string & owner_name, const int16_t & world_x, const int16_t & world_y, const unsigned_int_ptr & price, const bool & is_locked)
        {
            _data << house_id;
            _data << model_id;
            _data << owner_id;
            _data << owner_name;
            _data << world_x;
            _data << world_y;
            _data << price->buffer();
            _data << is_locked;
        }
        
        house_informations_inside(byte_buffer & data)
        {
            data >> house_id;
            data >> model_id;
            data >> owner_id;
            data >> owner_name;
            data >> world_x;
            data >> world_y;
            price = std::make_unique<unsigned_int>(data);
            data >> is_locked;
        }
    };
    
    using house_informations_inside_ptr = std::unique_ptr<house_informations_inside>;
}

#endif
