//  Generated by desperion protocol_builder

#ifndef core_object_ground_removed_message_hpp
#define core_object_ground_removed_message_hpp

namespace protocol
{
    struct object_ground_removed_message : dofus_unit
    {
        int16_t cell;
        
        int16_t id() const override
        { return 3014; } 
        
        object_ground_removed_message(const int16_t & cell)
        {
            _data << cell;
        }
        
        object_ground_removed_message(byte_buffer & data)
        {
            data >> cell;
        }
    };
}

#endif
