//  Generated by desperion protocol_builder

#ifndef core_object_ground_added_message_hpp
#define core_object_ground_added_message_hpp

namespace protocol
{
    struct object_ground_added_message : dofus_unit
    {
        int16_t cell_id;
        int16_t object_g_i_d;
        
        int16_t id() const override
        { return 3017; } 
        
        object_ground_added_message(const int16_t & cell_id, const int16_t & object_g_i_d)
        {
            _data << cell_id;
            _data << object_g_i_d;
        }
        
        object_ground_added_message(byte_buffer & data)
        {
            data >> cell_id;
            data >> object_g_i_d;
        }
    };
}

#endif
