//  Generated by desperion protocol_builder

#ifndef core_game_fight_placement_position_request_message_hpp
#define core_game_fight_placement_position_request_message_hpp

namespace network
{
    struct game_fight_placement_position_request_message : dofus_unit
    {
        int16_t cell_id;
        
        int16_t id() const override
        { return 704; } 
        
        game_fight_placement_position_request_message(const int16_t & cell_id)
        {
            _data << cell_id;
        }
        
        game_fight_placement_position_request_message(byte_buffer & data)
        {
            data >> cell_id;
        }
    };
}

#endif
