//  Generated by desperion protocol_builder

#ifndef core_player_status_hpp
#define core_player_status_hpp

namespace protocol
{
    struct player_status : dofus_unit
    {
        int8_t status_id;
        
        int16_t id() const override
        { return 415; } 
        
        player_status(const int8_t & status_id)
        {
            _data << status_id;
        }
        
        player_status(byte_buffer & data)
        {
            data >> status_id;
        }
    };
    
    using player_status_ptr = std::unique_ptr<player_status>;
}

#endif
