//  Generated by desperion protocol_builder

#ifndef core_server_session_constant_hpp
#define core_server_session_constant_hpp

namespace network
{
    struct server_session_constant : dofus_unit
    {
        int16_t id;
        
        int16_t id() const override
        { return 430; } 
        
        server_session_constant(const int16_t & id)
        {
            _data << id;
        }
        
        server_session_constant(byte_buffer & data)
        {
            data >> id;
        }
    };
    
    using server_session_constant_ptr = std::unique_ptr<server_session_constant>;
}

#endif
