//  Generated by desperion protocol_builder

#ifndef core_server_session_constant_string_hpp
#define core_server_session_constant_string_hpp

namespace network
{
    struct server_session_constant_string : server_session_constant
    {
        std::string value;
        
        int16_t id() const override
        { return 436; } 
        
        server_session_constant_string(const int16_t & id, const std::string & value) : server_session_constant { id }
        {
            _data << value;
        }
        
        server_session_constant_string(byte_buffer & data) : server_session_constant { data }
        {
            data >> value;
        }
    };
    
    using server_session_constant_string_ptr = std::unique_ptr<server_session_constant_string>;
}

#endif
