//  Generated by desperion protocol_builder

#ifndef d2fstream_achievement_category_hpp
#define d2fstream_achievement_category_hpp

namespace datacenter
{
    struct achievement_category : data_holder
    {
        int32_t id;
        int32_t name_id;
        int32_t parent_id;
        std::string icon;
        int32_t order;
        std::string color;
        std::vector<uint32_t> achievement_ids;
        
        achievement_category() = default;
        
        achievement_category(const int32_t & id, const int32_t & name_id, const int32_t & parent_id, const std::string & icon, const int32_t & order, const std::string & color, const std::vector<uint32_t> & achievement_ids) : id { id }, name_id { name_id }, parent_id { parent_id }, icon { icon }, order { order }, color { color }, achievement_ids { achievement_ids }
        {
        }
        
        achievement_category(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(name_id, data.second.at("nameId"));
            acquire(parent_id, data.second.at("parentId"));
            acquire(icon, data.second.at("icon"));
            acquire(order, data.second.at("order"));
            acquire(color, data.second.at("color"));
            acquire(achievement_ids, data.second.at("achievementIds"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<achievement_category>();
        release(id, data.second["id"], file);
        release(name_id, data.second["nameId"], file);
        release(parent_id, data.second["parentId"], file);
        release(icon, data.second["icon"], file);
        release(order, data.second["order"], file);
        release(color, data.second["color"], file);
        release(achievement_ids, data.second["achievementIds"], file);
        return data;
    }
#endif
}
#endif