//  Generated by desperion protocol_builder

#ifndef core_skill_action_description_craft_hpp
#define core_skill_action_description_craft_hpp

namespace network
{
    struct skill_action_description_craft : skill_action_description
    {
        int8_t max_slots;
        int8_t probability;
        
        int16_t id() const override
        { return 100; } 
        
        skill_action_description_craft(const int16_t & skill_id, const int8_t & max_slots, const int8_t & probability) : skill_action_description { skill_id }
        {
            _data << max_slots;
            _data << probability;
        }
        
        skill_action_description_craft(byte_buffer & data) : skill_action_description { data }
        {
            data >> max_slots;
            data >> probability;
        }
    };
    
    using skill_action_description_craft_ptr = std::unique_ptr<skill_action_description_craft>;
}

#endif
