//  Generated by desperion protocol_builder

#ifndef core_guild_emblem_hpp
#define core_guild_emblem_hpp

namespace protocol
{
    struct guild_emblem : dofus_unit
    {
        int16_t symbol_shape;
        int32_t symbol_color;
        int16_t background_shape;
        int32_t background_color;
        
        int16_t id() const override
        { return 87; } 
        
        guild_emblem(const int16_t & symbol_shape, const int32_t & symbol_color, const int16_t & background_shape, const int32_t & background_color)
        {
            _data << symbol_shape;
            _data << symbol_color;
            _data << background_shape;
            _data << background_color;
        }
        
        guild_emblem(byte_buffer & data)
        {
            data >> symbol_shape;
            data >> symbol_color;
            data >> background_shape;
            data >> background_color;
        }
    };
    
    using guild_emblem_ptr = std::unique_ptr<guild_emblem>;
}

#endif
