//  Generated by desperion protocol_builder

#ifndef core_character_minimal_plus_look_and_grade_informations_hpp
#define core_character_minimal_plus_look_and_grade_informations_hpp

namespace protocol
{
    struct character_minimal_plus_look_and_grade_informations : character_minimal_plus_look_informations
    {
        int32_t grade;
        
        int16_t id() const override
        { return 193; } 
        
        character_minimal_plus_look_and_grade_informations(const entity_look_ptr & entity_look, const int8_t & level, const std::string & name, const int32_t & id, const int32_t & grade) : character_minimal_plus_look_informations { entity_look,level,name,id }
        {
            _data << grade;
        }
        
        character_minimal_plus_look_and_grade_informations(byte_buffer & data) : character_minimal_plus_look_informations { data }
        {
            data >> grade;
        }
    };
    
    using character_minimal_plus_look_and_grade_informations_ptr = std::unique_ptr<character_minimal_plus_look_and_grade_informations>;
}

#endif
