//  Generated by desperion protocol_builder

#ifndef core_character_minimal_guild_informations_hpp
#define core_character_minimal_guild_informations_hpp

namespace protocol
{
    struct character_minimal_guild_informations : character_minimal_plus_look_informations
    {
        basic_guild_informations_ptr guild;
        
        int16_t id() const override
        { return 445; } 
        
        character_minimal_guild_informations(const entity_look_ptr & entity_look, const int8_t & level, const std::string & name, const int32_t & id, const basic_guild_informations_ptr & guild) : character_minimal_plus_look_informations { entity_look,level,name,id }
        {
            _data << guild->buffer();
        }
        
        character_minimal_guild_informations(byte_buffer & data) : character_minimal_plus_look_informations { data }
        {
            guild = std::make_unique<basic_guild_informations>(data);
        }
    };
    
    using character_minimal_guild_informations_ptr = std::unique_ptr<character_minimal_guild_informations>;
}

#endif
