//  Generated by desperion protocol_builder

#ifndef core_alliance_informations_hpp
#define core_alliance_informations_hpp

namespace network
{
    struct alliance_informations : basic_named_alliance_informations
    {
        guild_emblem_ptr alliance_emblem;
        
        int16_t id() const override
        { return 417; } 
        
        alliance_informations(const std::string & alliance_name, const int32_t & alliance_id, const std::string & alliance_tag, const guild_emblem_ptr & alliance_emblem) : basic_named_alliance_informations { alliance_name,alliance_id,alliance_tag }
        {
            _data << alliance_emblem->buffer();
        }
        
        alliance_informations(byte_buffer & data) : basic_named_alliance_informations { data }
        {
            alliance_emblem = std::make_unique<guild_emblem>(data);
        }
    };
    
    using alliance_informations_ptr = std::unique_ptr<alliance_informations>;
}

#endif
