//  Generated by desperion protocol_builder

#ifndef core_game_role_play_mount_informations_hpp
#define core_game_role_play_mount_informations_hpp

namespace protocol
{
    struct game_role_play_mount_informations : game_role_play_named_actor_informations
    {
        std::string owner_name;
        int8_t level;
        
        int16_t id() const override
        { return 180; } 
        
        game_role_play_mount_informations(const std::string & name, const int32_t & contextual_id, const entity_look_ptr & look, const entity_disposition_informations_ptr & disposition, const std::string & owner_name, const int8_t & level) : game_role_play_named_actor_informations { name,contextual_id,look,disposition }
        {
            _data << owner_name;
            _data << level;
        }
        
        game_role_play_mount_informations(byte_buffer & data) : game_role_play_named_actor_informations { data }
        {
            data >> owner_name;
            data >> level;
        }
    };
    
    using game_role_play_mount_informations_ptr = std::unique_ptr<game_role_play_mount_informations>;
}

#endif
