//  Generated by desperion protocol_builder

#ifndef core_game_role_play_npc_with_quest_informations_hpp
#define core_game_role_play_npc_with_quest_informations_hpp

namespace protocol
{
    struct game_role_play_npc_with_quest_informations : game_role_play_npc_informations
    {
        game_role_play_npc_quest_flag_ptr quest_flag;
        
        int16_t id() const override
        { return 383; } 
        
        game_role_play_npc_with_quest_informations(const int16_t & npc_id, const bool & sex, const int16_t & special_artwork_id, const int32_t & contextual_id, const entity_look_ptr & look, const entity_disposition_informations_ptr & disposition, const game_role_play_npc_quest_flag_ptr & quest_flag) : game_role_play_npc_informations { npc_id,sex,special_artwork_id,contextual_id,look,disposition }
        {
            _data << quest_flag->buffer();
        }
        
        game_role_play_npc_with_quest_informations(byte_buffer & data) : game_role_play_npc_informations { data }
        {
            quest_flag = std::make_unique<game_role_play_npc_quest_flag>(data);
        }
    };
    
    using game_role_play_npc_with_quest_informations_ptr = std::unique_ptr<game_role_play_npc_with_quest_informations>;
}

#endif
