//  Generated by desperion protocol_builder

#ifndef core_human_option_ornament_hpp
#define core_human_option_ornament_hpp

namespace network
{
    struct human_option_ornament : human_option
    {
        int16_t ornament_id;
        
        int16_t id() const override
        { return 411; } 
        
        human_option_ornament(const int16_t & ornament_id)
        {
            _data << ornament_id;
        }
        
        human_option_ornament(byte_buffer & data) : human_option { data }
        {
            data >> ornament_id;
        }
    };
    
    using human_option_ornament_ptr = std::unique_ptr<human_option_ornament>;
}

#endif
