//  Generated by desperion protocol_builder

#ifndef core_human_option_emote_hpp
#define core_human_option_emote_hpp

namespace network
{
    struct human_option_emote : human_option
    {
        int8_t emote_id;
        double emote_start_time;
        
        int16_t id() const override
        { return 407; } 
        
        human_option_emote(const int8_t & emote_id, const double & emote_start_time)
        {
            _data << emote_id;
            _data << emote_start_time;
        }
        
        human_option_emote(byte_buffer & data) : human_option { data }
        {
            data >> emote_id;
            data >> emote_start_time;
        }
    };
    
    using human_option_emote_ptr = std::unique_ptr<human_option_emote>;
}

#endif
