//  Generated by desperion protocol_builder

#ifndef core_human_option_object_use_hpp
#define core_human_option_object_use_hpp

namespace network
{
    struct human_option_object_use : human_option
    {
        int8_t delay_type_id;
        double delay_end_time;
        int16_t object_g_i_d;
        
        int16_t id() const override
        { return 449; } 
        
        human_option_object_use(const int8_t & delay_type_id, const double & delay_end_time, const int16_t & object_g_i_d)
        {
            _data << delay_type_id;
            _data << delay_end_time;
            _data << object_g_i_d;
        }
        
        human_option_object_use(byte_buffer & data) : human_option { data }
        {
            data >> delay_type_id;
            data >> delay_end_time;
            data >> object_g_i_d;
        }
    };
    
    using human_option_object_use_ptr = std::unique_ptr<human_option_object_use>;
}

#endif
