//  Generated by desperion protocol_builder

#ifndef core_human_option_title_hpp
#define core_human_option_title_hpp

namespace network
{
    struct human_option_title : human_option
    {
        int16_t title_id;
        std::string title_param;
        
        int16_t id() const override
        { return 408; } 
        
        human_option_title(const int16_t & title_id, const std::string & title_param)
        {
            _data << title_id;
            _data << title_param;
        }
        
        human_option_title(byte_buffer & data) : human_option { data }
        {
            data >> title_id;
            data >> title_param;
        }
    };
    
    using human_option_title_ptr = std::unique_ptr<human_option_title>;
}

#endif
