//  Generated by desperion protocol_builder

#ifndef core_object_item_in_role_play_hpp
#define core_object_item_in_role_play_hpp

namespace protocol
{
    struct object_item_in_role_play : dofus_unit
    {
        int16_t cell_id;
        int16_t object_g_i_d;
        
        int16_t id() const override
        { return 198; } 
        
        object_item_in_role_play(const int16_t & cell_id, const int16_t & object_g_i_d)
        {
            _data << cell_id;
            _data << object_g_i_d;
        }
        
        object_item_in_role_play(byte_buffer & data)
        {
            data >> cell_id;
            data >> object_g_i_d;
        }
    };
    
    using object_item_in_role_play_ptr = std::unique_ptr<object_item_in_role_play>;
}

#endif
