//  Generated by desperion protocol_builder

#ifndef core_tax_collector_guild_informations_hpp
#define core_tax_collector_guild_informations_hpp

namespace protocol
{
    struct tax_collector_guild_informations : tax_collector_complementary_informations
    {
        basic_guild_informations_ptr guild;
        
        int16_t id() const override
        { return 446; } 
        
        tax_collector_guild_informations(const basic_guild_informations_ptr & guild)
        {
            _data << guild->buffer();
        }
        
        tax_collector_guild_informations(byte_buffer & data) : tax_collector_complementary_informations { data }
        {
            guild = std::make_unique<basic_guild_informations>(data);
        }
    };
    
    using tax_collector_guild_informations_ptr = std::unique_ptr<tax_collector_guild_informations>;
}

#endif
