//  Generated by desperion protocol_builder

#ifndef core_character_level_up_message_hpp
#define core_character_level_up_message_hpp

namespace network
{
    struct character_level_up_message : dofus_unit
    {
        int8_t new_level;
        
        int16_t id() const override
        { return 5670; } 
        
        character_level_up_message(const int8_t & new_level)
        {
            _data << new_level;
        }
        
        character_level_up_message(byte_buffer & data)
        {
            data >> new_level;
        }
    };
}

#endif
