//  Generated by desperion protocol_builder

#ifndef core_game_server_informations_hpp
#define core_game_server_informations_hpp

namespace protocol
{
    struct game_server_informations : dofus_unit
    {
        int16_t _id;
        int8_t status;
        int8_t completion;
        bool is_selectable;
        int8_t characters_count;
        double date;
        
        int16_t id() const override
        { return 25; } 
        
        game_server_informations(const int16_t & _id, const int8_t & status, const int8_t & completion, const bool & is_selectable, const int8_t & characters_count, const double & date)
        {
            _data << _id;
            _data << status;
            _data << completion;
            _data << is_selectable;
            _data << characters_count;
            _data << date;
        }
        
        game_server_informations(byte_buffer & data)
        {
            data >> _id;
            data >> status;
            data >> completion;
            data >> is_selectable;
            data >> characters_count;
            data >> date;
        }
    };
    
    using game_server_informations_ptr = std::unique_ptr<game_server_informations>;
}

#endif
