//  Generated by desperion protocol_builder

#ifndef core_get_parts_list_message_hpp
#define core_get_parts_list_message_hpp

namespace protocol
{
    struct get_parts_list_message : dofus_unit
    {
        
        int16_t id() const override
        { return 1501; } 
        
        get_parts_list_message()
        {
        }
        
        get_parts_list_message(byte_buffer & data)
        {
        }
    };
}

#endif
