//  Generated by desperion protocol_builder

#ifndef core_character_spell_modification_hpp
#define core_character_spell_modification_hpp

namespace network
{
    struct character_spell_modification : dofus_unit
    {
        int8_t modification_type;
        int16_t spell_id;
        character_base_characteristic_ptr value;
        
        int16_t id() const override
        { return 215; } 
        
        character_spell_modification(const int8_t & modification_type, const int16_t & spell_id, const character_base_characteristic_ptr & value)
        {
            _data << modification_type;
            _data << spell_id;
            _data << value->buffer();
        }
        
        character_spell_modification(byte_buffer & data)
        {
            data >> modification_type;
            data >> spell_id;
            value = std::make_unique<character_base_characteristic>(data);
        }
    };
    
    using character_spell_modification_ptr = std::unique_ptr<character_spell_modification>;
}

#endif
