//  Generated by desperion protocol_builder

#ifndef core_game_context_move_element_message_hpp
#define core_game_context_move_element_message_hpp

namespace network
{
    struct game_context_move_element_message : dofus_unit
    {
        entity_movement_informations_ptr movement;
        
        int16_t id() const override
        { return 253; } 
        
        game_context_move_element_message(const entity_movement_informations_ptr & movement)
        {
            _data << movement->buffer();
        }
        
        game_context_move_element_message(byte_buffer & data)
        {
            movement = std::make_unique<entity_movement_informations>(data);
        }
    };
}

#endif
