//  Generated by desperion protocol_builder

#ifndef core_game_context_remove_element_message_hpp
#define core_game_context_remove_element_message_hpp

namespace network
{
    struct game_context_remove_element_message : dofus_unit
    {
        int32_t id;
        
        int16_t id() const override
        { return 251; } 
        
        game_context_remove_element_message(const int32_t & id)
        {
            _data << id;
        }
        
        game_context_remove_element_message(byte_buffer & data)
        {
            data >> id;
        }
    };
}

#endif
