//  Generated by desperion protocol_builder

#ifndef core_channel_enabling_change_message_hpp
#define core_channel_enabling_change_message_hpp

namespace protocol
{
    struct channel_enabling_change_message : dofus_unit
    {
        int8_t channel;
        bool enable;
        
        int16_t id() const override
        { return 891; } 
        
        channel_enabling_change_message(const int8_t & channel, const bool & enable)
        {
            _data << channel;
            _data << enable;
        }
        
        channel_enabling_change_message(byte_buffer & data)
        {
            data >> channel;
            data >> enable;
        }
    };
}

#endif
