//  Generated by desperion protocol_builder

#ifndef core_trust_status_message_hpp
#define core_trust_status_message_hpp

namespace protocol
{
    struct trust_status_message : dofus_unit
    {
        bool trusted;
        
        int16_t id() const override
        { return 6267; } 
        
        trust_status_message(const bool & trusted)
        {
            _data << trusted;
        }
        
        trust_status_message(byte_buffer & data)
        {
            data >> trusted;
        }
    };
}

#endif
