//  Generated by desperion protocol_builder

#ifndef core_acquaintance_search_error_message_hpp
#define core_acquaintance_search_error_message_hpp

namespace network
{
    struct acquaintance_search_error_message : dofus_unit
    {
        int8_t reason;
        
        int16_t id() const override
        { return 6143; } 
        
        acquaintance_search_error_message(const int8_t & reason)
        {
            _data << reason;
        }
        
        acquaintance_search_error_message(byte_buffer & data)
        {
            data >> reason;
        }
    };
}

#endif
