//  Generated by desperion protocol_builder

#ifndef core_prisms_list_register_message_hpp
#define core_prisms_list_register_message_hpp

namespace network
{
    struct prisms_list_register_message : dofus_unit
    {
        int8_t listen;
        
        int16_t id() const override
        { return 6441; } 
        
        prisms_list_register_message(const int8_t & listen)
        {
            _data << listen;
        }
        
        prisms_list_register_message(byte_buffer & data)
        {
            data >> listen;
        }
    };
}

#endif
