//  Generated by desperion protocol_builder

#ifndef core_prism_fight_defenders_swap_message_hpp
#define core_prism_fight_defenders_swap_message_hpp

namespace protocol
{
    struct prism_fight_defenders_swap_message : dofus_unit
    {
        int16_t sub_area_id;
        double fight_id;
        int32_t fighter_id_1;
        int32_t fighter_id_2;
        
        int16_t id() const override
        { return 5902; } 
        
        prism_fight_defenders_swap_message(const int16_t & sub_area_id, const double & fight_id, const int32_t & fighter_id_1, const int32_t & fighter_id_2)
        {
            _data << sub_area_id;
            _data << fight_id;
            _data << fighter_id_1;
            _data << fighter_id_2;
        }
        
        prism_fight_defenders_swap_message(byte_buffer & data)
        {
            data >> sub_area_id;
            data >> fight_id;
            data >> fighter_id_1;
            data >> fighter_id_2;
        }
    };
}

#endif
