//  Generated by desperion protocol_builder

#ifndef core_prism_use_request_message_hpp
#define core_prism_use_request_message_hpp

namespace protocol
{
    struct prism_use_request_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6041; } 
        
        prism_use_request_message()
        {
        }
        
        prism_use_request_message(byte_buffer & data)
        {
        }
    };
}

#endif
