//  Generated by desperion protocol_builder

#ifndef core_game_role_play_arena_update_player_infos_message_hpp
#define core_game_role_play_arena_update_player_infos_message_hpp

namespace protocol
{
    struct game_role_play_arena_update_player_infos_message : dofus_unit
    {
        int16_t rank;
        int16_t best_daily_rank;
        int16_t best_rank;
        int16_t victory_count;
        int16_t arena_fightcount;
        
        int16_t id() const override
        { return 6301; } 
        
        game_role_play_arena_update_player_infos_message(const int16_t & rank, const int16_t & best_daily_rank, const int16_t & best_rank, const int16_t & victory_count, const int16_t & arena_fightcount)
        {
            _data << rank;
            _data << best_daily_rank;
            _data << best_rank;
            _data << victory_count;
            _data << arena_fightcount;
        }
        
        game_role_play_arena_update_player_infos_message(byte_buffer & data)
        {
            data >> rank;
            data >> best_daily_rank;
            data >> best_rank;
            data >> victory_count;
            data >> arena_fightcount;
        }
    };
}

#endif
