//  Generated by desperion protocol_builder

#ifndef core_map_obstacle_hpp
#define core_map_obstacle_hpp

namespace protocol
{
    struct map_obstacle : dofus_unit
    {
        int16_t obstacle_cell_id;
        int8_t state;
        
        int16_t id() const override
        { return 200; } 
        
        map_obstacle(const int16_t & obstacle_cell_id, const int8_t & state)
        {
            _data << obstacle_cell_id;
            _data << state;
        }
        
        map_obstacle(byte_buffer & data)
        {
            data >> obstacle_cell_id;
            data >> state;
        }
    };
    
    using map_obstacle_ptr = std::unique_ptr<map_obstacle>;
}

#endif
