//  Generated by desperion protocol_builder

#ifndef core_exchange_bid_house_item_remove_ok_message_hpp
#define core_exchange_bid_house_item_remove_ok_message_hpp

namespace network
{
    struct exchange_bid_house_item_remove_ok_message : dofus_unit
    {
        int32_t seller_id;
        
        int16_t id() const override
        { return 5946; } 
        
        exchange_bid_house_item_remove_ok_message(const int32_t & seller_id)
        {
            _data << seller_id;
        }
        
        exchange_bid_house_item_remove_ok_message(byte_buffer & data)
        {
            data >> seller_id;
        }
    };
}

#endif
