//  Generated by desperion protocol_builder

#ifndef core_exchange_mount_stable_born_add_message_hpp
#define core_exchange_mount_stable_born_add_message_hpp

namespace network
{
    struct exchange_mount_stable_born_add_message : exchange_mount_stable_add_message
    {
        
        int16_t id() const override
        { return 5966; } 
        
        exchange_mount_stable_born_add_message(const mount_client_data_ptr & mount_description) : exchange_mount_stable_add_message { mount_description }
        {
        }
        
        exchange_mount_stable_born_add_message(byte_buffer & data) : exchange_mount_stable_add_message { data }
        {
        }
    };
}

#endif
