//  Generated by desperion protocol_builder

#ifndef core_exchange_item_auto_craft_remaining_message_hpp
#define core_exchange_item_auto_craft_remaining_message_hpp

namespace network
{
    struct exchange_item_auto_craft_remaining_message : dofus_unit
    {
        int32_t count;
        
        int16_t id() const override
        { return 6015; } 
        
        exchange_item_auto_craft_remaining_message(const int32_t & count)
        {
            _data << count;
        }
        
        exchange_item_auto_craft_remaining_message(byte_buffer & data)
        {
            data >> count;
        }
    };
}

#endif
