//  Generated by desperion protocol_builder

#ifndef core_job_experience_hpp
#define core_job_experience_hpp

namespace protocol
{
    struct job_experience : dofus_unit
    {
        int8_t job_id;
        int8_t job_level;
        double job_x_p;
        double job_xp_level_floor;
        double job_xp_next_level_floor;
        
        int16_t id() const override
        { return 98; } 
        
        job_experience(const int8_t & job_id, const int8_t & job_level, const double & job_x_p, const double & job_xp_level_floor, const double & job_xp_next_level_floor)
        {
            _data << job_id;
            _data << job_level;
            _data << job_x_p;
            _data << job_xp_level_floor;
            _data << job_xp_next_level_floor;
        }
        
        job_experience(byte_buffer & data)
        {
            data >> job_id;
            data >> job_level;
            data >> job_x_p;
            data >> job_xp_level_floor;
            data >> job_xp_next_level_floor;
        }
    };
    
    using job_experience_ptr = std::unique_ptr<job_experience>;
}

#endif
