//  Generated by desperion protocol_builder

#ifndef core_job_description_hpp
#define core_job_description_hpp

namespace protocol
{
    struct job_description : dofus_unit
    {
        int8_t job_id;
        std::vector<skill_action_description_ptr> skills;
        
        int16_t id() const override
        { return 101; } 
        
        job_description(const int8_t & job_id, const std::vector<skill_action_description_ptr> & skills)
        {
            _data << job_id;
            _data << static_cast<int16_t>(skills.size());
            for (auto && i : skills)
                _data << i->id() << i->buffer();
        }
        
        job_description(byte_buffer & data)
        {
            data >> job_id;
            int16_t skills_size;
            data >> skills_size;
            skills.resize(skills_size);
            for (int16_t i = 0; i < skills_size; ++i)
            {
                int16_t p;
                data >> p;
                skills[i].reset(type_manager::get_skill_action_description(p, data));
            }
        }
    };
    
    using job_description_ptr = std::unique_ptr<job_description>;
}

#endif
