//  Generated by desperion protocol_builder

#ifndef core_job_crafter_directory_settings_hpp
#define core_job_crafter_directory_settings_hpp

namespace protocol
{
    struct job_crafter_directory_settings : dofus_unit
    {
        int8_t job_id;
        int8_t min_slot;
        int8_t user_defined_params;
        
        int16_t id() const override
        { return 97; } 
        
        job_crafter_directory_settings(const int8_t & job_id, const int8_t & min_slot, const int8_t & user_defined_params)
        {
            _data << job_id;
            _data << min_slot;
            _data << user_defined_params;
        }
        
        job_crafter_directory_settings(byte_buffer & data)
        {
            data >> job_id;
            data >> min_slot;
            data >> user_defined_params;
        }
    };
    
    using job_crafter_directory_settings_ptr = std::unique_ptr<job_crafter_directory_settings>;
}

#endif
