//  Generated by desperion protocol_builder

#ifndef core_debug_in_client_message_hpp
#define core_debug_in_client_message_hpp

namespace network
{
    struct debug_in_client_message : dofus_unit
    {
        int8_t level;
        std::string message;
        
        int16_t id() const override
        { return 6028; } 
        
        debug_in_client_message(const int8_t & level, const std::string & message)
        {
            _data << level;
            _data << message;
        }
        
        debug_in_client_message(byte_buffer & data)
        {
            data >> level;
            data >> message;
        }
    };
}

#endif
