//  Generated by desperion protocol_builder

#ifndef core_debug_clear_highlight_cells_message_hpp
#define core_debug_clear_highlight_cells_message_hpp

namespace network
{
    struct debug_clear_highlight_cells_message : dofus_unit
    {
        
        int16_t id() const override
        { return 2002; } 
        
        debug_clear_highlight_cells_message()
        {
        }
        
        debug_clear_highlight_cells_message(byte_buffer & data)
        {
        }
    };
}

#endif
