//  Generated by desperion protocol_builder

#ifndef core_debug_highlight_cells_message_hpp
#define core_debug_highlight_cells_message_hpp

namespace network
{
    struct debug_highlight_cells_message : dofus_unit
    {
        int32_t color;
        std::vector<int16_t> cells;
        
        int16_t id() const override
        { return 2001; } 
        
        debug_highlight_cells_message(const int32_t & color, const std::vector<int16_t> & cells)
        {
            _data << color;
            _data << static_cast<int16_t>(cells.size());
            for (auto && i : cells)
                _data << i;
        }
        
        debug_highlight_cells_message(byte_buffer & data)
        {
            data >> color;
            int16_t cells_size;
            data >> cells_size;
            cells.resize(cells_size);
            for (int16_t i = 0; i < cells_size; ++i)
                data >> cells[i];
        }
    };
}

#endif
