//  Generated by desperion protocol_builder

#ifndef core_cinematic_message_hpp
#define core_cinematic_message_hpp

namespace network
{
    struct cinematic_message : dofus_unit
    {
        int16_t cinematic_id;
        
        int16_t id() const override
        { return 6053; } 
        
        cinematic_message(const int16_t & cinematic_id)
        {
            _data << cinematic_id;
        }
        
        cinematic_message(byte_buffer & data)
        {
            data >> cinematic_id;
        }
    };
}

#endif
