//  Generated by desperion protocol_builder

#ifndef core_u_r_l_open_message_hpp
#define core_u_r_l_open_message_hpp

namespace network
{
    struct u_r_l_open_message : dofus_unit
    {
        int32_t url_id;
        
        int16_t id() const override
        { return 6266; } 
        
        u_r_l_open_message(const int32_t & url_id)
        {
            _data << url_id;
        }
        
        u_r_l_open_message(byte_buffer & data)
        {
            data >> url_id;
        }
    };
}

#endif
