//  Generated by desperion protocol_builder

#ifndef core_game_role_play_npc_quest_flag_hpp
#define core_game_role_play_npc_quest_flag_hpp

namespace network
{
    struct game_role_play_npc_quest_flag : dofus_unit
    {
        std::vector<int16_t> quests_to_valid_id;
        std::vector<int16_t> quests_to_start_id;
        
        int16_t id() const override
        { return 384; } 
        
        game_role_play_npc_quest_flag(const std::vector<int16_t> & quests_to_valid_id, const std::vector<int16_t> & quests_to_start_id)
        {
            _data << static_cast<int16_t>(quests_to_valid_id.size());
            for (auto && i : quests_to_valid_id)
                _data << i;
            _data << static_cast<int16_t>(quests_to_start_id.size());
            for (auto && i : quests_to_start_id)
                _data << i;
        }
        
        game_role_play_npc_quest_flag(byte_buffer & data)
        {
            int16_t quests_to_valid_id_size;
            data >> quests_to_valid_id_size;
            quests_to_valid_id.resize(quests_to_valid_id_size);
            for (int16_t i = 0; i < quests_to_valid_id_size; ++i)
                data >> quests_to_valid_id[i];
            int16_t quests_to_start_id_size;
            data >> quests_to_start_id_size;
            quests_to_start_id.resize(quests_to_start_id_size);
            for (int16_t i = 0; i < quests_to_start_id_size; ++i)
                data >> quests_to_start_id[i];
        }
    };
    
    using game_role_play_npc_quest_flag_ptr = std::unique_ptr<game_role_play_npc_quest_flag>;
}

#endif
