//  Generated by desperion protocol_builder

#ifndef core_object_effect_string_hpp
#define core_object_effect_string_hpp

namespace network
{
    struct object_effect_string : object_effect
    {
        std::string value;
        
        int16_t id() const override
        { return 74; } 
        
        object_effect_string(const int16_t & action_id, const std::string & value) : object_effect { action_id }
        {
            _data << value;
        }
        
        object_effect_string(byte_buffer & data) : object_effect { data }
        {
            data >> value;
        }
    };
    
    using object_effect_string_ptr = std::unique_ptr<object_effect_string>;
}

#endif
