//  Generated by desperion protocol_builder

#ifndef core_dungeon_party_finder_register_error_message_hpp
#define core_dungeon_party_finder_register_error_message_hpp

namespace network
{
    struct dungeon_party_finder_register_error_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6243; } 
        
        dungeon_party_finder_register_error_message()
        {
        }
        
        dungeon_party_finder_register_error_message(byte_buffer & data)
        {
        }
    };
}

#endif
