//  Generated by desperion protocol_builder

#ifndef core_party_kicked_by_message_hpp
#define core_party_kicked_by_message_hpp

namespace network
{
    struct party_kicked_by_message : abstract_party_message
    {
        int32_t kicker_id;
        
        int16_t id() const override
        { return 5590; } 
        
        party_kicked_by_message(const int32_t & party_id, const int32_t & kicker_id) : abstract_party_message { party_id }
        {
            _data << kicker_id;
        }
        
        party_kicked_by_message(byte_buffer & data) : abstract_party_message { data }
        {
            data >> kicker_id;
        }
    };
}

#endif
