//  Generated by desperion protocol_builder

#ifndef core_party_loyalty_status_message_hpp
#define core_party_loyalty_status_message_hpp

namespace network
{
    struct party_loyalty_status_message : abstract_party_message
    {
        bool loyal;
        
        int16_t id() const override
        { return 6270; } 
        
        party_loyalty_status_message(const int32_t & party_id, const bool & loyal) : abstract_party_message { party_id }
        {
            _data << loyal;
        }
        
        party_loyalty_status_message(byte_buffer & data) : abstract_party_message { data }
        {
            data >> loyal;
        }
    };
}

#endif
