//  Generated by desperion protocol_builder

#ifndef core_game_role_play_remove_challenge_message_hpp
#define core_game_role_play_remove_challenge_message_hpp

namespace network
{
    struct game_role_play_remove_challenge_message : dofus_unit
    {
        int32_t fight_id;
        
        int16_t id() const override
        { return 300; } 
        
        game_role_play_remove_challenge_message(const int32_t & fight_id)
        {
            _data << fight_id;
        }
        
        game_role_play_remove_challenge_message(byte_buffer & data)
        {
            data >> fight_id;
        }
    };
}

#endif
