//  Generated by desperion protocol_builder

#ifndef core_lockable_show_code_dialog_message_hpp
#define core_lockable_show_code_dialog_message_hpp

namespace network
{
    struct lockable_show_code_dialog_message : dofus_unit
    {
        bool change_or_use;
        int8_t code_size;
        
        int16_t id() const override
        { return 5740; } 
        
        lockable_show_code_dialog_message(const bool & change_or_use, const int8_t & code_size)
        {
            _data << change_or_use;
            _data << code_size;
        }
        
        lockable_show_code_dialog_message(byte_buffer & data)
        {
            data >> change_or_use;
            data >> code_size;
        }
    };
}

#endif
