//  Generated by desperion protocol_builder

#ifndef d2fstream_alignment_side_hpp
#define d2fstream_alignment_side_hpp

namespace datacenter
{
    struct alignment_side : data_holder
    {
        int32_t id;
        int32_t name_id;
        bool can_conquest;
        
        alignment_side() = default;
        
        alignment_side(const int32_t & id, const int32_t & name_id, const bool & can_conquest) : id { id }, name_id { name_id }, can_conquest { can_conquest }
        {
        }
        
        alignment_side(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(name_id, data.second.at("nameId"));
            acquire(can_conquest, data.second.at("canConquest"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<alignment_side>();
        release(id, data.second["id"], file);
        release(name_id, data.second["nameId"], file);
        release(can_conquest, data.second["canConquest"], file);
        return data;
    }
#endif
}
#endif