//  Generated by desperion protocol_builder

#ifndef d2fstream_alignment_order_hpp
#define d2fstream_alignment_order_hpp

namespace datacenter
{
    struct alignment_order : data_holder
    {
        int32_t id;
        int32_t name_id;
        int32_t side_id;
        
        alignment_order() = default;
        
        alignment_order(const int32_t & id, const int32_t & name_id, const int32_t & side_id) : id { id }, name_id { name_id }, side_id { side_id }
        {
        }
        
        alignment_order(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(name_id, data.second.at("nameId"));
            acquire(side_id, data.second.at("sideId"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<alignment_order>();
        release(id, data.second["id"], file);
        release(name_id, data.second["nameId"], file);
        release(side_id, data.second["sideId"], file);
        return data;
    }
#endif
}
#endif