//  Generated by desperion protocol_builder

#ifndef d2fstream_alignment_effect_hpp
#define d2fstream_alignment_effect_hpp

namespace datacenter
{
    struct alignment_effect : data_holder
    {
        int32_t id;
        int32_t characteristic_id;
        int32_t description_id;
        
        alignment_effect() = default;
        
        alignment_effect(const int32_t & id, const int32_t & characteristic_id, const int32_t & description_id) : id { id }, characteristic_id { characteristic_id }, description_id { description_id }
        {
        }
        
        alignment_effect(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(characteristic_id, data.second.at("characteristicId"));
            acquire(description_id, data.second.at("descriptionId"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<alignment_effect>();
        release(id, data.second["id"], file);
        release(characteristic_id, data.second["characteristicId"], file);
        release(description_id, data.second["descriptionId"], file);
        return data;
    }
#endif
}
#endif