//  Generated by desperion protocol_builder

#ifndef core_lockable_state_update_abstract_message_hpp
#define core_lockable_state_update_abstract_message_hpp

namespace network
{
    struct lockable_state_update_abstract_message : dofus_unit
    {
        bool locked;
        
        int16_t id() const override
        { return 5671; } 
        
        lockable_state_update_abstract_message(const bool & locked)
        {
            _data << locked;
        }
        
        lockable_state_update_abstract_message(byte_buffer & data)
        {
            data >> locked;
        }
    };
}

#endif
