//  Generated by desperion protocol_builder

#ifndef core_emote_list_message_hpp
#define core_emote_list_message_hpp

namespace protocol
{
    struct emote_list_message : dofus_unit
    {
        std::vector<int8_t> emote_ids;
        
        int16_t id() const override
        { return 5689; } 
        
        emote_list_message(const std::vector<int8_t> & emote_ids)
        {
            _data << emote_ids;
        }
        
        emote_list_message(byte_buffer & data)
        {
            data >> emote_ids;
        }
    };
}

#endif
