//  Generated by desperion protocol_builder

#ifndef core_account_house_informations_hpp
#define core_account_house_informations_hpp

namespace protocol
{
    struct account_house_informations : dofus_unit
    {
        int32_t house_id;
        int16_t model_id;
        int16_t world_x;
        int16_t world_y;
        int32_t map_id;
        int16_t sub_area_id;
        
        int16_t id() const override
        { return 390; } 
        
        account_house_informations(const int32_t & house_id, const int16_t & model_id, const int16_t & world_x, const int16_t & world_y, const int32_t & map_id, const int16_t & sub_area_id)
        {
            _data << house_id;
            _data << model_id;
            _data << world_x;
            _data << world_y;
            _data << map_id;
            _data << sub_area_id;
        }
        
        account_house_informations(byte_buffer & data)
        {
            data >> house_id;
            data >> model_id;
            data >> world_x;
            data >> world_y;
            data >> map_id;
            data >> sub_area_id;
        }
    };
    
    using account_house_informations_ptr = std::unique_ptr<account_house_informations>;
}

#endif
