//  Generated by desperion protocol_builder

#ifndef core_house_informations_extended_hpp
#define core_house_informations_extended_hpp

namespace protocol
{
    struct house_informations_extended : house_informations
    {
        guild_informations_ptr guild_info;
        
        int16_t id() const override
        { return 112; } 
        
        house_informations_extended(const bool & is_on_sale, const bool & is_sale_locked, const int32_t & house_id, const std::vector<int32_t> & doors_on_map, const std::string & owner_name, const int16_t & model_id, const guild_informations_ptr & guild_info) : house_informations { is_on_sale,is_sale_locked,house_id,doors_on_map,owner_name,model_id }
        {
            _data << guild_info->buffer();
        }
        
        house_informations_extended(byte_buffer & data) : house_informations { data }
        {
            guild_info = std::make_unique<guild_informations>(data);
        }
    };
    
    using house_informations_extended_ptr = std::unique_ptr<house_informations_extended>;
}

#endif
