//  Generated by desperion protocol_builder

#ifndef core_house_properties_message_hpp
#define core_house_properties_message_hpp

namespace protocol
{
    struct house_properties_message : dofus_unit
    {
        house_informations_ptr properties;
        
        int16_t id() const override
        { return 5734; } 
        
        house_properties_message(const house_informations_ptr & properties)
        {
            _data << properties->id() << properties->buffer();
        }
        
        house_properties_message(byte_buffer & data)
        {
            int16_t properties_id;
            data >> properties_id;
            properties.reset(type_manager::get_house_informations(properties_id, data));
        }
    };
}

#endif
