//  Generated by desperion protocol_builder

#ifndef core_house_guild_none_message_hpp
#define core_house_guild_none_message_hpp

namespace protocol
{
    struct house_guild_none_message : dofus_unit
    {
        int16_t house_id;
        
        int16_t id() const override
        { return 5701; } 
        
        house_guild_none_message(const int16_t & house_id)
        {
            _data << house_id;
        }
        
        house_guild_none_message(byte_buffer & data)
        {
            data >> house_id;
        }
    };
}

#endif
