//  Generated by desperion protocol_builder

#ifndef core_object_item_information_with_quantity_hpp
#define core_object_item_information_with_quantity_hpp

namespace protocol
{
    struct object_item_information_with_quantity : object_item_minimal_information
    {
        int32_t quantity;
        
        int16_t id() const override
        { return 387; } 
        
        object_item_information_with_quantity(const int16_t & object_g_i_d, const int16_t & power_rate, const bool & over_max, const std::vector<object_effect_ptr> & effects, const int32_t & quantity) : object_item_minimal_information { object_g_i_d,power_rate,over_max,effects }
        {
            _data << quantity;
        }
        
        object_item_information_with_quantity(byte_buffer & data) : object_item_minimal_information { data }
        {
            data >> quantity;
        }
    };
    
    using object_item_information_with_quantity_ptr = std::unique_ptr<object_item_information_with_quantity>;
}

#endif
