//  Generated by desperion protocol_builder

#ifndef core_spell_item_hpp
#define core_spell_item_hpp

namespace protocol
{
    struct spell_item : item
    {
        int8_t position;
        int32_t spell_id;
        int8_t spell_level;
        
        int16_t id() const override
        { return 49; } 
        
        spell_item(const int8_t & position, const int32_t & spell_id, const int8_t & spell_level)
        {
            _data << position;
            _data << spell_id;
            _data << spell_level;
        }
        
        spell_item(byte_buffer & data) : item { data }
        {
            data >> position;
            data >> spell_id;
            data >> spell_level;
        }
    };
    
    using spell_item_ptr = std::unique_ptr<spell_item>;
}

#endif
