//  Generated by desperion protocol_builder

#ifndef core_admin_command_message_hpp
#define core_admin_command_message_hpp

namespace network
{
    struct admin_command_message : dofus_unit
    {
        std::string content;
        
        int16_t id() const override
        { return 76; } 
        
        admin_command_message(const std::string & content)
        {
            _data << content;
        }
        
        admin_command_message(byte_buffer & data)
        {
            data >> content;
        }
    };
}

#endif
