//  Generated by desperion protocol_builder

#ifndef core_identification_failed_message_hpp
#define core_identification_failed_message_hpp

namespace network
{
    struct identification_failed_message : dofus_unit
    {
        int8_t reason;
        
        int16_t id() const override
        { return 20; } 
        
        identification_failed_message(const int8_t & reason)
        {
            _data << reason;
        }
        
        identification_failed_message(byte_buffer & data)
        {
            data >> reason;
        }
    };
}

#endif
