//  Generated by desperion protocol_builder

#ifndef core_krosmaster_inventory_request_message_hpp
#define core_krosmaster_inventory_request_message_hpp

namespace protocol
{
    struct krosmaster_inventory_request_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6344; } 
        
        krosmaster_inventory_request_message()
        {
        }
        
        krosmaster_inventory_request_message(byte_buffer & data)
        {
        }
    };
}

#endif
