//  Generated by desperion protocol_builder

#ifndef core_krosmaster_auth_token_request_message_hpp
#define core_krosmaster_auth_token_request_message_hpp

namespace network
{
    struct krosmaster_auth_token_request_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6346; } 
        
        krosmaster_auth_token_request_message()
        {
        }
        
        krosmaster_auth_token_request_message(byte_buffer & data)
        {
        }
    };
}

#endif
