//  Generated by desperion protocol_builder

#ifndef core_chat_server_copy_message_hpp
#define core_chat_server_copy_message_hpp

namespace protocol
{
    struct chat_server_copy_message : chat_abstract_server_message
    {
        int32_t receiver_id;
        std::string receiver_name;
        
        int16_t id() const override
        { return 882; } 
        
        chat_server_copy_message(const int8_t & channel, const std::string & content, const int32_t & timestamp, const std::string & fingerprint, const int32_t & receiver_id, const std::string & receiver_name) : chat_abstract_server_message { channel,content,timestamp,fingerprint }
        {
            _data << receiver_id;
            _data << receiver_name;
        }
        
        chat_server_copy_message(byte_buffer & data) : chat_abstract_server_message { data }
        {
            data >> receiver_id;
            data >> receiver_name;
        }
    };
}

#endif
