//  Generated by desperion protocol_builder

#ifndef core_chat_client_multi_message_hpp
#define core_chat_client_multi_message_hpp

namespace protocol
{
    struct chat_client_multi_message : chat_abstract_client_message
    {
        int8_t channel;
        
        int16_t id() const override
        { return 861; } 
        
        chat_client_multi_message(const std::string & content, const int8_t & channel) : chat_abstract_client_message { content }
        {
            _data << channel;
        }
        
        chat_client_multi_message(byte_buffer & data) : chat_abstract_client_message { data }
        {
            data >> channel;
        }
    };
}

#endif
