//  Generated by desperion protocol_builder

#ifndef core_player_status_extended_hpp
#define core_player_status_extended_hpp

namespace network
{
    struct player_status_extended : player_status
    {
        std::string message;
        
        int16_t id() const override
        { return 414; } 
        
        player_status_extended(const int8_t & status_id, const std::string & message) : player_status { status_id }
        {
            _data << message;
        }
        
        player_status_extended(byte_buffer & data) : player_status { data }
        {
            data >> message;
        }
    };
    
    using player_status_extended_ptr = std::unique_ptr<player_status_extended>;
}

#endif
