//  Generated by desperion protocol_builder

#ifndef core_exchange_object_put_in_bag_message_hpp
#define core_exchange_object_put_in_bag_message_hpp

namespace network
{
    struct exchange_object_put_in_bag_message : exchange_object_message
    {
        object_item_ptr object;
        
        int16_t id() const override
        { return 6009; } 
        
        exchange_object_put_in_bag_message(const bool & remote, const object_item_ptr & object) : exchange_object_message { remote }
        {
            _data << object->buffer();
        }
        
        exchange_object_put_in_bag_message(byte_buffer & data) : exchange_object_message { data }
        {
            object = std::make_unique<object_item>(data);
        }
    };
}

#endif
