//  Generated by desperion protocol_builder

#ifndef core_gold_added_message_hpp
#define core_gold_added_message_hpp

namespace network
{
    struct gold_added_message : dofus_unit
    {
        gold_item_ptr gold;
        
        int16_t id() const override
        { return 6030; } 
        
        gold_added_message(const gold_item_ptr & gold)
        {
            _data << gold->buffer();
        }
        
        gold_added_message(byte_buffer & data)
        {
            gold = std::make_unique<gold_item>(data);
        }
    };
}

#endif
