//  Generated by desperion protocol_builder

#ifndef core_party_invitation_member_informations_hpp
#define core_party_invitation_member_informations_hpp

namespace protocol
{
    struct party_invitation_member_informations : character_base_informations
    {
        int16_t world_x;
        int16_t world_y;
        int32_t map_id;
        int16_t sub_area_id;
        
        int16_t id() const override
        { return 376; } 
        
        party_invitation_member_informations(const int8_t & breed, const bool & sex, const entity_look_ptr & entity_look, const int8_t & level, const std::string & name, const int32_t & id, const int16_t & world_x, const int16_t & world_y, const int32_t & map_id, const int16_t & sub_area_id) : character_base_informations { breed,sex,entity_look,level,name,id }
        {
            _data << world_x;
            _data << world_y;
            _data << map_id;
            _data << sub_area_id;
        }
        
        party_invitation_member_informations(byte_buffer & data) : character_base_informations { data }
        {
            data >> world_x;
            data >> world_y;
            data >> map_id;
            data >> sub_area_id;
        }
    };
    
    using party_invitation_member_informations_ptr = std::unique_ptr<party_invitation_member_informations>;
}

#endif
