//  Generated by desperion protocol_builder

#ifndef core_authentication_ticket_accepted_message_hpp
#define core_authentication_ticket_accepted_message_hpp

namespace protocol
{
    struct authentication_ticket_accepted_message : dofus_unit
    {
        
        int16_t id() const override
        { return 111; } 
        
        authentication_ticket_accepted_message()
        {
        }
        
        authentication_ticket_accepted_message(byte_buffer & data)
        {
        }
    };
}

#endif
