//  Generated by desperion protocol_builder

#ifndef core_exchange_multi_craft_set_crafter_can_use_his_ressources_message_hpp
#define core_exchange_multi_craft_set_crafter_can_use_his_ressources_message_hpp

namespace network
{
    struct exchange_multi_craft_set_crafter_can_use_his_ressources_message : dofus_unit
    {
        bool allow;
        
        int16_t id() const override
        { return 6021; } 
        
        exchange_multi_craft_set_crafter_can_use_his_ressources_message(const bool & allow)
        {
            _data << allow;
        }
        
        exchange_multi_craft_set_crafter_can_use_his_ressources_message(byte_buffer & data)
        {
            data >> allow;
        }
    };
}

#endif
