//  Generated by desperion protocol_builder

#ifndef core_inventory_content_message_hpp
#define core_inventory_content_message_hpp

namespace network
{
    struct inventory_content_message : dofus_unit
    {
        std::vector<object_item_ptr> objects;
        int32_t kamas;
        
        int16_t id() const override
        { return 3016; } 
        
        inventory_content_message(const std::vector<object_item_ptr> & objects, const int32_t & kamas)
        {
            _data << static_cast<int16_t>(objects.size());
            for (auto && i : objects)
                _data << i->buffer();
            _data << kamas;
        }
        
        inventory_content_message(byte_buffer & data)
        {
            int16_t objects_size;
            data >> objects_size;
            objects.resize(objects_size);
            for (int16_t i = 0; i < objects_size; ++i)
                objects[i] = std::make_unique<object_item>(data);
            data >> kamas;
        }
    };
}

#endif
