//  Generated by desperion protocol_builder

#ifndef core_object_deleted_message_hpp
#define core_object_deleted_message_hpp

namespace protocol
{
    struct object_deleted_message : dofus_unit
    {
        int32_t object_u_i_d;
        
        int16_t id() const override
        { return 3024; } 
        
        object_deleted_message(const int32_t & object_u_i_d)
        {
            _data << object_u_i_d;
        }
        
        object_deleted_message(byte_buffer & data)
        {
            data >> object_u_i_d;
        }
    };
}

#endif
