//  Generated by desperion protocol_builder

#ifndef core_object_added_message_hpp
#define core_object_added_message_hpp

namespace network
{
    struct object_added_message : dofus_unit
    {
        object_item_ptr object;
        
        int16_t id() const override
        { return 3025; } 
        
        object_added_message(const object_item_ptr & object)
        {
            _data << object->buffer();
        }
        
        object_added_message(byte_buffer & data)
        {
            object = std::make_unique<object_item>(data);
        }
    };
}

#endif
