//  Generated by desperion protocol_builder

#ifndef core_objects_added_message_hpp
#define core_objects_added_message_hpp

namespace protocol
{
    struct objects_added_message : dofus_unit
    {
        std::vector<object_item_ptr> object;
        
        int16_t id() const override
        { return 6033; } 
        
        objects_added_message(const std::vector<object_item_ptr> & object)
        {
            _data << static_cast<int16_t>(object.size());
            for (auto && i : object)
                _data << i->buffer();
        }
        
        objects_added_message(byte_buffer & data)
        {
            int16_t object_size;
            data >> object_size;
            object.resize(object_size);
            for (int16_t i = 0; i < object_size; ++i)
                object[i] = std::make_unique<object_item>(data);
        }
    };
}

#endif
