//  Generated by desperion protocol_builder

#ifndef core_console_commands_list_message_hpp
#define core_console_commands_list_message_hpp

namespace network
{
    struct console_commands_list_message : dofus_unit
    {
        std::vector<std::string> aliases;
        std::vector<std::string> descriptions;
        
        int16_t id() const override
        { return 6127; } 
        
        console_commands_list_message(const std::vector<std::string> & aliases, const std::vector<std::string> & descriptions)
        {
            _data << static_cast<int16_t>(aliases.size());
            for (auto && i : aliases)
                _data << i;
            _data << static_cast<int16_t>(descriptions.size());
            for (auto && i : descriptions)
                _data << i;
        }
        
        console_commands_list_message(byte_buffer & data)
        {
            int16_t aliases_size;
            data >> aliases_size;
            aliases.resize(aliases_size);
            for (int16_t i = 0; i < aliases_size; ++i)
                data >> aliases[i];
            int16_t descriptions_size;
            data >> descriptions_size;
            descriptions.resize(descriptions_size);
            for (int16_t i = 0; i < descriptions_size; ++i)
                data >> descriptions[i];
        }
    };
}

#endif
