//  Generated by desperion protocol_builder

#ifndef d2fstream_skin_mapping_hpp
#define d2fstream_skin_mapping_hpp

namespace datacenter
{
    struct skin_mapping : data_holder
    {
        int32_t id;
        int32_t low_def_id;
        
        skin_mapping() = default;
        
        skin_mapping(const int32_t & id, const int32_t & low_def_id) : id { id }, low_def_id { low_def_id }
        {
        }
        
        skin_mapping(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(low_def_id, data.second.at("lowDefId"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<skin_mapping>();
        release(id, data.second["id"], file);
        release(low_def_id, data.second["lowDefId"], file);
        return data;
    }
#endif
}
#endif