//  Generated by desperion protocol_builder

#ifndef core_guild_fight_take_place_request_message_hpp
#define core_guild_fight_take_place_request_message_hpp

namespace network
{
    struct guild_fight_take_place_request_message : guild_fight_join_request_message
    {
        int32_t replaced_character_id;
        
        int16_t id() const override
        { return 6235; } 
        
        guild_fight_take_place_request_message(const int32_t & tax_collector_id, const int32_t & replaced_character_id) : guild_fight_join_request_message { tax_collector_id }
        {
            _data << replaced_character_id;
        }
        
        guild_fight_take_place_request_message(byte_buffer & data) : guild_fight_join_request_message { data }
        {
            data >> replaced_character_id;
        }
    };
}

#endif
