//  Generated by desperion protocol_builder

#ifndef core_tax_collector_movement_message_hpp
#define core_tax_collector_movement_message_hpp

namespace protocol
{
    struct tax_collector_movement_message : dofus_unit
    {
        bool hire_or_fire;
        tax_collector_basic_informations_ptr basic_infos;
        int32_t player_id;
        std::string player_name;
        
        int16_t id() const override
        { return 5633; } 
        
        tax_collector_movement_message(const bool & hire_or_fire, const tax_collector_basic_informations_ptr & basic_infos, const int32_t & player_id, const std::string & player_name)
        {
            _data << hire_or_fire;
            _data << basic_infos->buffer();
            _data << player_id;
            _data << player_name;
        }
        
        tax_collector_movement_message(byte_buffer & data)
        {
            data >> hire_or_fire;
            basic_infos = std::make_unique<tax_collector_basic_informations>(data);
            data >> player_id;
            data >> player_name;
        }
    };
}

#endif
