//  Generated by desperion protocol_builder

#ifndef d2fstream_chat_channel_hpp
#define d2fstream_chat_channel_hpp

namespace datacenter
{
    struct chat_channel : data_holder
    {
        int32_t id;
        int32_t name_id;
        int32_t description_id;
        std::string shortcut;
        std::string shortcut_key;
        bool is_private;
        bool allow_objects;
        
        chat_channel() = default;
        
        chat_channel(const int32_t & id, const int32_t & name_id, const int32_t & description_id, const std::string & shortcut, const std::string & shortcut_key, const bool & is_private, const bool & allow_objects) : id { id }, name_id { name_id }, description_id { description_id }, shortcut { shortcut }, shortcut_key { shortcut_key }, is_private { is_private }, allow_objects { allow_objects }
        {
        }
        
        chat_channel(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(name_id, data.second.at("nameId"));
            acquire(description_id, data.second.at("descriptionId"));
            acquire(shortcut, data.second.at("shortcut"));
            acquire(shortcut_key, data.second.at("shortcutKey"));
            acquire(is_private, data.second.at("isPrivate"));
            acquire(allow_objects, data.second.at("allowObjects"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<chat_channel>();
        release(id, data.second["id"], file);
        release(name_id, data.second["nameId"], file);
        release(description_id, data.second["descriptionId"], file);
        release(shortcut, data.second["shortcut"], file);
        release(shortcut_key, data.second["shortcutKey"], file);
        release(is_private, data.second["isPrivate"], file);
        release(allow_objects, data.second["allowObjects"], file);
        return data;
    }
#endif
}
#endif