//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_slide_message_hpp
#define core_game_action_fight_slide_message_hpp

namespace network
{
    struct game_action_fight_slide_message : abstract_game_action_message
    {
        int32_t target_id;
        int16_t start_cell_id;
        int16_t end_cell_id;
        
        int16_t id() const override
        { return 5525; } 
        
        game_action_fight_slide_message(const int16_t & action_id, const int32_t & source_id, const int32_t & target_id, const int16_t & start_cell_id, const int16_t & end_cell_id) : abstract_game_action_message { action_id,source_id }
        {
            _data << target_id;
            _data << start_cell_id;
            _data << end_cell_id;
        }
        
        game_action_fight_slide_message(byte_buffer & data) : abstract_game_action_message { data }
        {
            data >> target_id;
            data >> start_cell_id;
            data >> end_cell_id;
        }
    };
}

#endif
