//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_life_and_shield_points_lost_message_hpp
#define core_game_action_fight_life_and_shield_points_lost_message_hpp

namespace network
{
    struct game_action_fight_life_and_shield_points_lost_message : game_action_fight_life_points_lost_message
    {
        int16_t shield_loss;
        
        int16_t id() const override
        { return 6310; } 
        
        game_action_fight_life_and_shield_points_lost_message(const int32_t & target_id, const int16_t & loss, const int16_t & permanent_damages, const int16_t & action_id, const int32_t & source_id, const int16_t & shield_loss) : game_action_fight_life_points_lost_message { target_id,loss,permanent_damages,action_id,source_id }
        {
            _data << shield_loss;
        }
        
        game_action_fight_life_and_shield_points_lost_message(byte_buffer & data) : game_action_fight_life_points_lost_message { data }
        {
            data >> shield_loss;
        }
    };
}

#endif
