//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_mark_cells_message_hpp
#define core_game_action_fight_mark_cells_message_hpp

namespace network
{
    struct game_action_fight_mark_cells_message : abstract_game_action_message
    {
        game_action_mark_ptr mark;
        
        int16_t id() const override
        { return 5540; } 
        
        game_action_fight_mark_cells_message(const int16_t & action_id, const int32_t & source_id, const game_action_mark_ptr & mark) : abstract_game_action_message { action_id,source_id }
        {
            _data << mark->buffer();
        }
        
        game_action_fight_mark_cells_message(byte_buffer & data) : abstract_game_action_message { data }
        {
            mark = std::make_unique<game_action_mark>(data);
        }
    };
}

#endif
