//  Generated by desperion protocol_builder

#ifndef d2fstream_item_criterion_factory_hpp
#define d2fstream_item_criterion_factory_hpp

namespace datacenter
{
    struct item_criterion_factory : data_holder
    {
        
        item_criterion_factory()
        {
        }
        
        item_criterion_factory(data_object && data)
        {
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<item_criterion_factory>();
        return data;
    }
#endif
}
#endif