//  Generated by desperion protocol_builder

#ifndef core_abstract_contact_informations_hpp
#define core_abstract_contact_informations_hpp

namespace network
{
    struct abstract_contact_informations : dofus_unit
    {
        int32_t account_id;
        std::string account_name;
        
        int16_t id() const override
        { return 380; } 
        
        abstract_contact_informations(const int32_t & account_id, const std::string & account_name)
        {
            _data << account_id;
            _data << account_name;
        }
        
        abstract_contact_informations(byte_buffer & data)
        {
            data >> account_id;
            data >> account_name;
        }
    };
    
    using abstract_contact_informations_ptr = std::unique_ptr<abstract_contact_informations>;
}

#endif
