//  Generated by desperion protocol_builder

#ifndef core_notification_update_flag_message_hpp
#define core_notification_update_flag_message_hpp

namespace network
{
    struct notification_update_flag_message : dofus_unit
    {
        int16_t index;
        
        int16_t id() const override
        { return 6090; } 
        
        notification_update_flag_message(const int16_t & index)
        {
            _data << index;
        }
        
        notification_update_flag_message(byte_buffer & data)
        {
            data >> index;
        }
    };
}

#endif
