//  Generated by desperion protocol_builder

#ifndef core_paddock_informations_for_sell_hpp
#define core_paddock_informations_for_sell_hpp

namespace network
{
    struct paddock_informations_for_sell : dofus_unit
    {
        std::string guild_owner;
        int16_t world_x;
        int16_t world_y;
        int16_t sub_area_id;
        int8_t nb_mount;
        int8_t nb_object;
        int32_t price;
        
        int16_t id() const override
        { return 222; } 
        
        paddock_informations_for_sell(const std::string & guild_owner, const int16_t & world_x, const int16_t & world_y, const int16_t & sub_area_id, const int8_t & nb_mount, const int8_t & nb_object, const int32_t & price)
        {
            _data << guild_owner;
            _data << world_x;
            _data << world_y;
            _data << sub_area_id;
            _data << nb_mount;
            _data << nb_object;
            _data << price;
        }
        
        paddock_informations_for_sell(byte_buffer & data)
        {
            data >> guild_owner;
            data >> world_x;
            data >> world_y;
            data >> sub_area_id;
            data >> nb_mount;
            data >> nb_object;
            data >> price;
        }
    };
    
    using paddock_informations_for_sell_ptr = std::unique_ptr<paddock_informations_for_sell>;
}

#endif
