//  Generated by desperion protocol_builder

#ifndef core_map_complementary_informations_data_in_house_message_hpp
#define core_map_complementary_informations_data_in_house_message_hpp

namespace network
{
    struct map_complementary_informations_data_in_house_message : map_complementary_informations_data_message
    {
        house_informations_inside_ptr current_house;
        
        int16_t id() const override
        { return 6130; } 
        
        map_complementary_informations_data_in_house_message(const int16_t & sub_area_id, const int32_t & map_id, const std::vector<house_informations_ptr> & houses, const std::vector<game_role_play_actor_informations_ptr> & actors, const std::vector<interactive_element_ptr> & interactive_elements, const std::vector<stated_element_ptr> & stated_elements, const std::vector<map_obstacle_ptr> & obstacles, const std::vector<fight_common_informations_ptr> & fights, const house_informations_inside_ptr & current_house) : map_complementary_informations_data_message { sub_area_id,map_id,houses,actors,interactive_elements,stated_elements,obstacles,fights }
        {
            _data << current_house->buffer();
        }
        
        map_complementary_informations_data_in_house_message(byte_buffer & data) : map_complementary_informations_data_message { data }
        {
            current_house = std::make_unique<house_informations_inside>(data);
        }
    };
}

#endif
