//  Generated by desperion protocol_builder

#ifndef core_teleport_on_same_map_message_hpp
#define core_teleport_on_same_map_message_hpp

namespace network
{
    struct teleport_on_same_map_message : dofus_unit
    {
        int32_t target_id;
        int16_t cell_id;
        
        int16_t id() const override
        { return 6048; } 
        
        teleport_on_same_map_message(const int32_t & target_id, const int16_t & cell_id)
        {
            _data << target_id;
            _data << cell_id;
        }
        
        teleport_on_same_map_message(byte_buffer & data)
        {
            data >> target_id;
            data >> cell_id;
        }
    };
}

#endif
