//  Generated by desperion protocol_builder

#ifndef core_character_name_suggestion_success_message_hpp
#define core_character_name_suggestion_success_message_hpp

namespace protocol
{
    struct character_name_suggestion_success_message : dofus_unit
    {
        std::string suggestion;
        
        int16_t id() const override
        { return 5544; } 
        
        character_name_suggestion_success_message(const std::string & suggestion)
        {
            _data << suggestion;
        }
        
        character_name_suggestion_success_message(byte_buffer & data)
        {
            data >> suggestion;
        }
    };
}

#endif
