//  Generated by desperion protocol_builder

#ifndef core_alliance_left_message_hpp
#define core_alliance_left_message_hpp

namespace protocol
{
    struct alliance_left_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6398; } 
        
        alliance_left_message()
        {
        }
        
        alliance_left_message(byte_buffer & data)
        {
        }
    };
}

#endif
