//  Generated by desperion protocol_builder

#ifndef core_alliance_modification_valid_message_hpp
#define core_alliance_modification_valid_message_hpp

namespace protocol
{
    struct alliance_modification_valid_message : dofus_unit
    {
        std::string alliance_name;
        std::string alliance_tag;
        guild_emblem_ptr alliancemblem;
        
        int16_t id() const override
        { return 6450; } 
        
        alliance_modification_valid_message(const std::string & alliance_name, const std::string & alliance_tag, const guild_emblem_ptr & alliancemblem)
        {
            _data << alliance_name;
            _data << alliance_tag;
            _data << alliancemblem->buffer();
        }
        
        alliance_modification_valid_message(byte_buffer & data)
        {
            data >> alliance_name;
            data >> alliance_tag;
            alliancemblem = std::make_unique<guild_emblem>(data);
        }
    };
}

#endif
