//  Generated by desperion protocol_builder

#ifndef core_alliance_partial_list_message_hpp
#define core_alliance_partial_list_message_hpp

namespace protocol
{
    struct alliance_partial_list_message : alliance_list_message
    {
        
        int16_t id() const override
        { return 6427; } 
        
        alliance_partial_list_message(const std::vector<alliance_fact_sheet_informations_ptr> & alliances) : alliance_list_message { alliances }
        {
        }
        
        alliance_partial_list_message(byte_buffer & data) : alliance_list_message { data }
        {
        }
    };
}

#endif
