//  Generated by desperion protocol_builder

#ifndef core_alliance_insider_info_request_message_hpp
#define core_alliance_insider_info_request_message_hpp

namespace network
{
    struct alliance_insider_info_request_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6417; } 
        
        alliance_insider_info_request_message()
        {
        }
        
        alliance_insider_info_request_message(byte_buffer & data)
        {
        }
    };
}

#endif
