//  Generated by desperion protocol_builder

#ifndef core_ornament_selected_message_hpp
#define core_ornament_selected_message_hpp

namespace network
{
    struct ornament_selected_message : dofus_unit
    {
        int16_t ornament_id;
        
        int16_t id() const override
        { return 6369; } 
        
        ornament_selected_message(const int16_t & ornament_id)
        {
            _data << ornament_id;
        }
        
        ornament_selected_message(byte_buffer & data)
        {
            data >> ornament_id;
        }
    };
}

#endif
