//  Generated by desperion protocol_builder

#ifndef core_ornament_select_error_message_hpp
#define core_ornament_select_error_message_hpp

namespace protocol
{
    struct ornament_select_error_message : dofus_unit
    {
        int8_t reason;
        
        int16_t id() const override
        { return 6370; } 
        
        ornament_select_error_message(const int8_t & reason)
        {
            _data << reason;
        }
        
        ornament_select_error_message(byte_buffer & data)
        {
            data >> reason;
        }
    };
}

#endif
