//  Generated by desperion protocol_builder

#ifndef core_title_gained_message_hpp
#define core_title_gained_message_hpp

namespace protocol
{
    struct title_gained_message : dofus_unit
    {
        int16_t title_id;
        
        int16_t id() const override
        { return 6364; } 
        
        title_gained_message(const int16_t & title_id)
        {
            _data << title_id;
        }
        
        title_gained_message(byte_buffer & data)
        {
            data >> title_id;
        }
    };
}

#endif
