//  Generated by desperion protocol_builder

#ifndef core_title_selected_message_hpp
#define core_title_selected_message_hpp

namespace network
{
    struct title_selected_message : dofus_unit
    {
        int16_t title_id;
        
        int16_t id() const override
        { return 6366; } 
        
        title_selected_message(const int16_t & title_id)
        {
            _data << title_id;
        }
        
        title_selected_message(byte_buffer & data)
        {
            data >> title_id;
        }
    };
}

#endif
