//  Generated by desperion protocol_builder

#ifndef core_character_replay_with_recolor_request_message_hpp
#define core_character_replay_with_recolor_request_message_hpp

namespace network
{
    struct character_replay_with_recolor_request_message : character_replay_request_message
    {
        std::vector<int32_t> indexed_color;
        
        int16_t id() const override
        { return 6111; } 
        
        character_replay_with_recolor_request_message(const int32_t & character_id, const std::vector<int32_t> & indexed_color) : character_replay_request_message { character_id }
        {
            _data << static_cast<int16_t>(indexed_color.size());
            for (auto && i : indexed_color)
                _data << i;
        }
        
        character_replay_with_recolor_request_message(byte_buffer & data) : character_replay_request_message { data }
        {
            int16_t indexed_color_size;
            data >> indexed_color_size;
            indexed_color.resize(indexed_color_size);
            for (int16_t i = 0; i < indexed_color_size; ++i)
                data >> indexed_color[i];
        }
    };
}

#endif
