//  Generated by desperion protocol_builder

#ifndef core_interactive_use_ended_message_hpp
#define core_interactive_use_ended_message_hpp

namespace protocol
{
    struct interactive_use_ended_message : dofus_unit
    {
        int32_t elem_id;
        int16_t skill_id;
        
        int16_t id() const override
        { return 6112; } 
        
        interactive_use_ended_message(const int32_t & elem_id, const int16_t & skill_id)
        {
            _data << elem_id;
            _data << skill_id;
        }
        
        interactive_use_ended_message(byte_buffer & data)
        {
            data >> elem_id;
            data >> skill_id;
        }
    };
}

#endif
