//  Generated by desperion protocol_builder

#ifndef core_stated_element_updated_message_hpp
#define core_stated_element_updated_message_hpp

namespace protocol
{
    struct stated_element_updated_message : dofus_unit
    {
        stated_element_ptr stated_element;
        
        int16_t id() const override
        { return 5709; } 
        
        stated_element_updated_message(const stated_element_ptr & stated_element)
        {
            _data << stated_element->buffer();
        }
        
        stated_element_updated_message(byte_buffer & data)
        {
            stated_element = std::make_unique<stated_element>(data);
        }
    };
}

#endif
