//  Generated by desperion protocol_builder

#ifndef core_entity_disposition_informations_hpp
#define core_entity_disposition_informations_hpp

namespace network
{
    struct entity_disposition_informations : dofus_unit
    {
        int16_t cell_id;
        int8_t direction;
        
        int16_t id() const override
        { return 60; } 
        
        entity_disposition_informations(const int16_t & cell_id, const int8_t & direction)
        {
            _data << cell_id;
            _data << direction;
        }
        
        entity_disposition_informations(byte_buffer & data)
        {
            data >> cell_id;
            data >> direction;
        }
    };
    
    using entity_disposition_informations_ptr = std::unique_ptr<entity_disposition_informations>;
}

#endif
