//  Generated by desperion protocol_builder

#ifndef core_game_context_refresh_entity_look_message_hpp
#define core_game_context_refresh_entity_look_message_hpp

namespace protocol
{
    struct game_context_refresh_entity_look_message : dofus_unit
    {
        int32_t id;
        entity_look_ptr look;
        
        int16_t id() const override
        { return 5637; } 
        
        game_context_refresh_entity_look_message(const int32_t & id, const entity_look_ptr & look)
        {
            _data << id;
            _data << look->buffer();
        }
        
        game_context_refresh_entity_look_message(byte_buffer & data)
        {
            data >> id;
            look = std::make_unique<entity_look>(data);
        }
    };
}

#endif
