//  Generated by desperion protocol_builder

#ifndef core_game_map_movement_cancel_message_hpp
#define core_game_map_movement_cancel_message_hpp

namespace protocol
{
    struct game_map_movement_cancel_message : dofus_unit
    {
        int16_t cell_id;
        
        int16_t id() const override
        { return 953; } 
        
        game_map_movement_cancel_message(const int16_t & cell_id)
        {
            _data << cell_id;
        }
        
        game_map_movement_cancel_message(byte_buffer & data)
        {
            data >> cell_id;
        }
    };
}

#endif
