//  Generated by desperion protocol_builder

#ifndef core_game_map_change_orientations_message_hpp
#define core_game_map_change_orientations_message_hpp

namespace network
{
    struct game_map_change_orientations_message : dofus_unit
    {
        std::vector<actor_orientation_ptr> orientations;
        
        int16_t id() const override
        { return 6155; } 
        
        game_map_change_orientations_message(const std::vector<actor_orientation_ptr> & orientations)
        {
            _data << static_cast<int16_t>(orientations.size());
            for (auto && i : orientations)
                _data << i->buffer();
        }
        
        game_map_change_orientations_message(byte_buffer & data)
        {
            int16_t orientations_size;
            data >> orientations_size;
            orientations.resize(orientations_size);
            for (int16_t i = 0; i < orientations_size; ++i)
                orientations[i] = std::make_unique<actor_orientation>(data);
        }
    };
}

#endif
