//  Generated by desperion protocol_builder

#ifndef core_game_context_move_multiple_elements_message_hpp
#define core_game_context_move_multiple_elements_message_hpp

namespace protocol
{
    struct game_context_move_multiple_elements_message : dofus_unit
    {
        std::vector<entity_movement_informations_ptr> movements;
        
        int16_t id() const override
        { return 254; } 
        
        game_context_move_multiple_elements_message(const std::vector<entity_movement_informations_ptr> & movements)
        {
            _data << static_cast<int16_t>(movements.size());
            for (auto && i : movements)
                _data << i->buffer();
        }
        
        game_context_move_multiple_elements_message(byte_buffer & data)
        {
            int16_t movements_size;
            data >> movements_size;
            movements.resize(movements_size);
            for (int16_t i = 0; i < movements_size; ++i)
                movements[i] = std::make_unique<entity_movement_informations>(data);
        }
    };
}

#endif
