//  Generated by desperion protocol_builder

#ifndef core_game_map_movement_message_hpp
#define core_game_map_movement_message_hpp

namespace protocol
{
    struct game_map_movement_message : dofus_unit
    {
        std::vector<int16_t> key_movements;
        int32_t actor_id;
        
        int16_t id() const override
        { return 951; } 
        
        game_map_movement_message(const std::vector<int16_t> & key_movements, const int32_t & actor_id)
        {
            _data << static_cast<int16_t>(key_movements.size());
            for (auto && i : key_movements)
                _data << i;
            _data << actor_id;
        }
        
        game_map_movement_message(byte_buffer & data)
        {
            int16_t key_movements_size;
            data >> key_movements_size;
            key_movements.resize(key_movements_size);
            for (int16_t i = 0; i < key_movements_size; ++i)
                data >> key_movements[i];
            data >> actor_id;
        }
    };
}

#endif
