//  Generated by desperion protocol_builder

#ifndef core_show_cell_message_hpp
#define core_show_cell_message_hpp

namespace protocol
{
    struct show_cell_message : dofus_unit
    {
        int32_t source_id;
        int16_t cell_id;
        
        int16_t id() const override
        { return 5612; } 
        
        show_cell_message(const int32_t & source_id, const int16_t & cell_id)
        {
            _data << source_id;
            _data << cell_id;
        }
        
        show_cell_message(byte_buffer & data)
        {
            data >> source_id;
            data >> cell_id;
        }
    };
}

#endif
