//  Generated by desperion protocol_builder

#ifndef core_show_cell_spectator_message_hpp
#define core_show_cell_spectator_message_hpp

namespace protocol
{
    struct show_cell_spectator_message : show_cell_message
    {
        std::string player_name;
        
        int16_t id() const override
        { return 6158; } 
        
        show_cell_spectator_message(const int32_t & source_id, const int16_t & cell_id, const std::string & player_name) : show_cell_message { source_id,cell_id }
        {
            _data << player_name;
        }
        
        show_cell_spectator_message(byte_buffer & data) : show_cell_message { data }
        {
            data >> player_name;
        }
    };
}

#endif
