//  Generated by desperion protocol_builder

#ifndef core_mount_set_message_hpp
#define core_mount_set_message_hpp

namespace network
{
    struct mount_set_message : dofus_unit
    {
        mount_client_data_ptr mount_data;
        
        int16_t id() const override
        { return 5968; } 
        
        mount_set_message(const mount_client_data_ptr & mount_data)
        {
            _data << mount_data->buffer();
        }
        
        mount_set_message(byte_buffer & data)
        {
            mount_data = std::make_unique<mount_client_data>(data);
        }
    };
}

#endif
