//  Generated by desperion protocol_builder

#ifndef core_mount_xp_ratio_message_hpp
#define core_mount_xp_ratio_message_hpp

namespace network
{
    struct mount_xp_ratio_message : dofus_unit
    {
        int8_t ratio;
        
        int16_t id() const override
        { return 5970; } 
        
        mount_xp_ratio_message(const int8_t & ratio)
        {
            _data << ratio;
        }
        
        mount_xp_ratio_message(byte_buffer & data)
        {
            data >> ratio;
        }
    };
}

#endif
