//  Generated by desperion protocol_builder

#ifndef core_mount_information_request_message_hpp
#define core_mount_information_request_message_hpp

namespace network
{
    struct mount_information_request_message : dofus_unit
    {
        double id;
        double time;
        
        int16_t id() const override
        { return 5972; } 
        
        mount_information_request_message(const double & id, const double & time)
        {
            _data << id;
            _data << time;
        }
        
        mount_information_request_message(byte_buffer & data)
        {
            data >> id;
            data >> time;
        }
    };
}

#endif
