//  Generated by desperion protocol_builder

#ifndef core_object_average_prices_message_hpp
#define core_object_average_prices_message_hpp

namespace network
{
    struct object_average_prices_message : dofus_unit
    {
        std::vector<int16_t> ids;
        std::vector<int32_t> avg_prices;
        
        int16_t id() const override
        { return 6335; } 
        
        object_average_prices_message(const std::vector<int16_t> & ids, const std::vector<int32_t> & avg_prices)
        {
            _data << static_cast<int16_t>(ids.size());
            for (auto && i : ids)
                _data << i;
            _data << static_cast<int16_t>(avg_prices.size());
            for (auto && i : avg_prices)
                _data << i;
        }
        
        object_average_prices_message(byte_buffer & data)
        {
            int16_t ids_size;
            data >> ids_size;
            ids.resize(ids_size);
            for (int16_t i = 0; i < ids_size; ++i)
                data >> ids[i];
            int16_t avg_prices_size;
            data >> avg_prices_size;
            avg_prices.resize(avg_prices_size);
            for (int16_t i = 0; i < avg_prices_size; ++i)
                data >> avg_prices[i];
        }
    };
}

#endif
