//  Generated by desperion protocol_builder

#ifndef core_actor_orientation_hpp
#define core_actor_orientation_hpp

namespace network
{
    struct actor_orientation : dofus_unit
    {
        int32_t id;
        int8_t direction;
        
        int16_t id() const override
        { return 353; } 
        
        actor_orientation(const int32_t & id, const int8_t & direction)
        {
            _data << id;
            _data << direction;
        }
        
        actor_orientation(byte_buffer & data)
        {
            data >> id;
            data >> direction;
        }
    };
    
    using actor_orientation_ptr = std::unique_ptr<actor_orientation>;
}

#endif
