//  Generated by desperion protocol_builder

#ifndef core_achievement_finished_message_hpp
#define core_achievement_finished_message_hpp

namespace protocol
{
    struct achievement_finished_message : dofus_unit
    {
        int16_t id;
        int16_t finishedlevel;
        
        int16_t id() const override
        { return 6208; } 
        
        achievement_finished_message(const int16_t & id, const int16_t & finishedlevel)
        {
            _data << id;
            _data << finishedlevel;
        }
        
        achievement_finished_message(byte_buffer & data)
        {
            data >> id;
            data >> finishedlevel;
        }
    };
}

#endif
