//  Generated by desperion protocol_builder

#ifndef core_achievement_details_message_hpp
#define core_achievement_details_message_hpp

namespace protocol
{
    struct achievement_details_message : dofus_unit
    {
        achievement_ptr achievement;
        
        int16_t id() const override
        { return 6378; } 
        
        achievement_details_message(const achievement_ptr & achievement)
        {
            _data << achievement->buffer();
        }
        
        achievement_details_message(byte_buffer & data)
        {
            achievement = std::make_unique<achievement>(data);
        }
    };
}

#endif
