//  Generated by desperion protocol_builder

#ifndef core_achievement_reward_error_message_hpp
#define core_achievement_reward_error_message_hpp

namespace protocol
{
    struct achievement_reward_error_message : dofus_unit
    {
        int16_t achievement_id;
        
        int16_t id() const override
        { return 6375; } 
        
        achievement_reward_error_message(const int16_t & achievement_id)
        {
            _data << achievement_id;
        }
        
        achievement_reward_error_message(byte_buffer & data)
        {
            data >> achievement_id;
        }
    };
}

#endif
