//  Generated by desperion protocol_builder

#ifndef core_job_crafter_directory_entry_request_message_hpp
#define core_job_crafter_directory_entry_request_message_hpp

namespace protocol
{
    struct job_crafter_directory_entry_request_message : dofus_unit
    {
        int32_t player_id;
        
        int16_t id() const override
        { return 6043; } 
        
        job_crafter_directory_entry_request_message(const int32_t & player_id)
        {
            _data << player_id;
        }
        
        job_crafter_directory_entry_request_message(byte_buffer & data)
        {
            data >> player_id;
        }
    };
}

#endif
