//  Generated by desperion protocol_builder

#ifndef core_paddock_to_sell_filter_message_hpp
#define core_paddock_to_sell_filter_message_hpp

namespace network
{
    struct paddock_to_sell_filter_message : dofus_unit
    {
        int32_t area_id;
        int8_t at_least_nb_mount;
        int8_t at_least_nb_machine;
        int32_t max_price;
        
        int16_t id() const override
        { return 6161; } 
        
        paddock_to_sell_filter_message(const int32_t & area_id, const int8_t & at_least_nb_mount, const int8_t & at_least_nb_machine, const int32_t & max_price)
        {
            _data << area_id;
            _data << at_least_nb_mount;
            _data << at_least_nb_machine;
            _data << max_price;
        }
        
        paddock_to_sell_filter_message(byte_buffer & data)
        {
            data >> area_id;
            data >> at_least_nb_mount;
            data >> at_least_nb_machine;
            data >> max_price;
        }
    };
}

#endif
