//  Generated by desperion protocol_builder

#ifndef core_paddock_properties_message_hpp
#define core_paddock_properties_message_hpp

namespace protocol
{
    struct paddock_properties_message : dofus_unit
    {
        paddock_informations_ptr properties;
        
        int16_t id() const override
        { return 5824; } 
        
        paddock_properties_message(const paddock_informations_ptr & properties)
        {
            _data << properties->id() << properties->buffer();
        }
        
        paddock_properties_message(byte_buffer & data)
        {
            int16_t properties_id;
            data >> properties_id;
            properties.reset(type_manager::get_paddock_informations(properties_id, data));
        }
    };
}

#endif
