//  Generated by desperion protocol_builder

#ifndef core_game_role_play_prism_informations_hpp
#define core_game_role_play_prism_informations_hpp

namespace network
{
    struct game_role_play_prism_informations : game_role_play_actor_informations
    {
        prism_information_ptr prism;
        
        int16_t id() const override
        { return 161; } 
        
        game_role_play_prism_informations(const int32_t & contextual_id, const entity_look_ptr & look, const entity_disposition_informations_ptr & disposition, const prism_information_ptr & prism) : game_role_play_actor_informations { contextual_id,look,disposition }
        {
            _data << prism->id() << prism->buffer();
        }
        
        game_role_play_prism_informations(byte_buffer & data) : game_role_play_actor_informations { data }
        {
            int16_t prism_id;
            data >> prism_id;
            prism.reset(type_manager::get_prism_information(prism_id, data));
        }
    };
    
    using game_role_play_prism_informations_ptr = std::unique_ptr<game_role_play_prism_informations>;
}

#endif
