//  Generated by desperion protocol_builder

#ifndef core_game_role_play_actor_informations_hpp
#define core_game_role_play_actor_informations_hpp

namespace network
{
    struct game_role_play_actor_informations : game_context_actor_informations
    {
        
        int16_t id() const override
        { return 141; } 
        
        game_role_play_actor_informations(const int32_t & contextual_id, const entity_look_ptr & look, const entity_disposition_informations_ptr & disposition) : game_context_actor_informations { contextual_id,look,disposition }
        {
        }
        
        game_role_play_actor_informations(byte_buffer & data) : game_context_actor_informations { data }
        {
        }
    };
    
    using game_role_play_actor_informations_ptr = std::unique_ptr<game_role_play_actor_informations>;
}

#endif
