//  Generated by desperion protocol_builder

#ifndef core_startup_actions_list_message_hpp
#define core_startup_actions_list_message_hpp

namespace protocol
{
    struct startup_actions_list_message : dofus_unit
    {
        std::vector<startup_action_add_object_ptr> actions;
        
        int16_t id() const override
        { return 1301; } 
        
        startup_actions_list_message(const std::vector<startup_action_add_object_ptr> & actions)
        {
            _data << static_cast<int16_t>(actions.size());
            for (auto && i : actions)
                _data << i->buffer();
        }
        
        startup_actions_list_message(byte_buffer & data)
        {
            int16_t actions_size;
            data >> actions_size;
            actions.resize(actions_size);
            for (int16_t i = 0; i < actions_size; ++i)
                actions[i] = std::make_unique<startup_action_add_object>(data);
        }
    };
}

#endif
