//  Generated by desperion protocol_builder

#ifndef core_actor_alignment_informations_hpp
#define core_actor_alignment_informations_hpp

namespace protocol
{
    struct actor_alignment_informations : dofus_unit
    {
        int8_t alignment_side;
        int8_t alignment_value;
        int8_t alignment_grade;
        int32_t character_power;
        
        int16_t id() const override
        { return 201; } 
        
        actor_alignment_informations(const int8_t & alignment_side, const int8_t & alignment_value, const int8_t & alignment_grade, const int32_t & character_power)
        {
            _data << alignment_side;
            _data << alignment_value;
            _data << alignment_grade;
            _data << character_power;
        }
        
        actor_alignment_informations(byte_buffer & data)
        {
            data >> alignment_side;
            data >> alignment_value;
            data >> alignment_grade;
            data >> character_power;
        }
    };
    
    using actor_alignment_informations_ptr = std::unique_ptr<actor_alignment_informations>;
}

#endif
