//  Generated by desperion protocol_builder

#ifndef core_actor_extended_alignment_informations_hpp
#define core_actor_extended_alignment_informations_hpp

namespace network
{
    struct actor_extended_alignment_informations : actor_alignment_informations
    {
        int16_t honor;
        int16_t honor_grade_floor;
        int16_t honor_next_grade_floor;
        int8_t aggressable;
        
        int16_t id() const override
        { return 202; } 
        
        actor_extended_alignment_informations(const int8_t & alignment_side, const int8_t & alignment_value, const int8_t & alignment_grade, const int32_t & character_power, const int16_t & honor, const int16_t & honor_grade_floor, const int16_t & honor_next_grade_floor, const int8_t & aggressable) : actor_alignment_informations { alignment_side,alignment_value,alignment_grade,character_power }
        {
            _data << honor;
            _data << honor_grade_floor;
            _data << honor_next_grade_floor;
            _data << aggressable;
        }
        
        actor_extended_alignment_informations(byte_buffer & data) : actor_alignment_informations { data }
        {
            data >> honor;
            data >> honor_grade_floor;
            data >> honor_next_grade_floor;
            data >> aggressable;
        }
    };
    
    using actor_extended_alignment_informations_ptr = std::unique_ptr<actor_extended_alignment_informations>;
}

#endif
