//  Generated by desperion protocol_builder

#ifndef core_krosmaster_transfer_request_message_hpp
#define core_krosmaster_transfer_request_message_hpp

namespace network
{
    struct krosmaster_transfer_request_message : dofus_unit
    {
        std::string uid;
        
        int16_t id() const override
        { return 6349; } 
        
        krosmaster_transfer_request_message(const std::string & uid)
        {
            _data << uid;
        }
        
        krosmaster_transfer_request_message(byte_buffer & data)
        {
            data >> uid;
        }
    };
}

#endif
