//  Generated by desperion protocol_builder

#ifndef d2fstream_rank_name_hpp
#define d2fstream_rank_name_hpp

namespace datacenter
{
    struct rank_name : data_holder
    {
        int32_t id;
        int32_t name_id;
        int32_t order;
        
        rank_name() = default;
        
        rank_name(const int32_t & id, const int32_t & name_id, const int32_t & order) : id { id }, name_id { name_id }, order { order }
        {
        }
        
        rank_name(data_object && data)
        {
            acquire(id, data.second.at("id"));
            acquire(name_id, data.second.at("nameId"));
            acquire(order, data.second.at("order"));
        }
        
        data_object to_d2o(const d2o_writer &);
    };

#ifdef d2fstream_d2o_writer_hpp
    data_object to_d2o(const d2o_writer & file)
    {
        data_object data;
        data.first = file.get_class_id_for_type<rank_name>();
        release(id, data.second["id"], file);
        release(name_id, data.second["nameId"], file);
        release(order, data.second["order"], file);
        return data;
    }
#endif
}
#endif