//  Generated by desperion protocol_builder

#ifndef core_titles_and_ornaments_list_message_hpp
#define core_titles_and_ornaments_list_message_hpp

namespace network
{
    struct titles_and_ornaments_list_message : dofus_unit
    {
        std::vector<int16_t> titles;
        std::vector<int16_t> ornaments;
        int16_t active_title;
        int16_t active_ornament;
        
        int16_t id() const override
        { return 6367; } 
        
        titles_and_ornaments_list_message(const std::vector<int16_t> & titles, const std::vector<int16_t> & ornaments, const int16_t & active_title, const int16_t & active_ornament)
        {
            _data << static_cast<int16_t>(titles.size());
            for (auto && i : titles)
                _data << i;
            _data << static_cast<int16_t>(ornaments.size());
            for (auto && i : ornaments)
                _data << i;
            _data << active_title;
            _data << active_ornament;
        }
        
        titles_and_ornaments_list_message(byte_buffer & data)
        {
            int16_t titles_size;
            data >> titles_size;
            titles.resize(titles_size);
            for (int16_t i = 0; i < titles_size; ++i)
                data >> titles[i];
            int16_t ornaments_size;
            data >> ornaments_size;
            ornaments.resize(ornaments_size);
            for (int16_t i = 0; i < ornaments_size; ++i)
                data >> ornaments[i];
            data >> active_title;
            data >> active_ornament;
        }
    };
}

#endif
