//  Generated by desperion protocol_builder

#ifndef core_exchange_replay_count_modified_message_hpp
#define core_exchange_replay_count_modified_message_hpp

namespace protocol
{
    struct exchange_replay_count_modified_message : dofus_unit
    {
        int32_t count;
        
        int16_t id() const override
        { return 6023; } 
        
        exchange_replay_count_modified_message(const int32_t & count)
        {
            _data << count;
        }
        
        exchange_replay_count_modified_message(byte_buffer & data)
        {
            data >> count;
        }
    };
}

#endif
