//  Generated by desperion protocol_builder

#ifndef core_exchange_request_on_mount_stock_message_hpp
#define core_exchange_request_on_mount_stock_message_hpp

namespace protocol
{
    struct exchange_request_on_mount_stock_message : dofus_unit
    {
        
        int16_t id() const override
        { return 5986; } 
        
        exchange_request_on_mount_stock_message()
        {
        }
        
        exchange_request_on_mount_stock_message(byte_buffer & data)
        {
        }
    };
}

#endif
