//  Generated by desperion protocol_builder

#ifndef core_exchange_started_with_storage_message_hpp
#define core_exchange_started_with_storage_message_hpp

namespace protocol
{
    struct exchange_started_with_storage_message : exchange_started_message
    {
        int32_t storage_max_slot;
        
        int16_t id() const override
        { return 6236; } 
        
        exchange_started_with_storage_message(const int8_t & exchange_type, const int32_t & storage_max_slot) : exchange_started_message { exchange_type }
        {
            _data << storage_max_slot;
        }
        
        exchange_started_with_storage_message(byte_buffer & data) : exchange_started_message { data }
        {
            data >> storage_max_slot;
        }
    };
}

#endif
