//  Generated by desperion protocol_builder

#ifndef core_exchange_start_as_vendor_message_hpp
#define core_exchange_start_as_vendor_message_hpp

namespace protocol
{
    struct exchange_start_as_vendor_message : dofus_unit
    {
        
        int16_t id() const override
        { return 5775; } 
        
        exchange_start_as_vendor_message()
        {
        }
        
        exchange_start_as_vendor_message(byte_buffer & data)
        {
        }
    };
}

#endif
