//  Generated by desperion protocol_builder

#ifndef core_exchange_replay_stop_message_hpp
#define core_exchange_replay_stop_message_hpp

namespace protocol
{
    struct exchange_replay_stop_message : dofus_unit
    {
        
        int16_t id() const override
        { return 6001; } 
        
        exchange_replay_stop_message()
        {
        }
        
        exchange_replay_stop_message(byte_buffer & data)
        {
        }
    };
}

#endif
