//  Generated by desperion protocol_builder

#ifndef core_exchange_bid_search_ok_message_hpp
#define core_exchange_bid_search_ok_message_hpp

namespace network
{
    struct exchange_bid_search_ok_message : dofus_unit
    {
        
        int16_t id() const override
        { return 5802; } 
        
        exchange_bid_search_ok_message()
        {
        }
        
        exchange_bid_search_ok_message(byte_buffer & data)
        {
        }
    };
}

#endif
