//  Generated by desperion protocol_builder

#ifndef core_exchange_start_ok_job_index_message_hpp
#define core_exchange_start_ok_job_index_message_hpp

namespace protocol
{
    struct exchange_start_ok_job_index_message : dofus_unit
    {
        std::vector<int32_t> jobs;
        
        int16_t id() const override
        { return 5819; } 
        
        exchange_start_ok_job_index_message(const std::vector<int32_t> & jobs)
        {
            _data << static_cast<int16_t>(jobs.size());
            for (auto && i : jobs)
                _data << i;
        }
        
        exchange_start_ok_job_index_message(byte_buffer & data)
        {
            int16_t jobs_size;
            data >> jobs_size;
            jobs.resize(jobs_size);
            for (int16_t i = 0; i < jobs_size; ++i)
                data >> jobs[i];
        }
    };
}

#endif
