//  Generated by desperion protocol_builder

#ifndef core_exchange_bid_house_search_message_hpp
#define core_exchange_bid_house_search_message_hpp

namespace protocol
{
    struct exchange_bid_house_search_message : dofus_unit
    {
        int32_t type;
        int32_t gen_id;
        
        int16_t id() const override
        { return 5806; } 
        
        exchange_bid_house_search_message(const int32_t & type, const int32_t & gen_id)
        {
            _data << type;
            _data << gen_id;
        }
        
        exchange_bid_house_search_message(byte_buffer & data)
        {
            data >> type;
            data >> gen_id;
        }
    };
}

#endif
