//  Generated by desperion protocol_builder

#ifndef core_exchange_mount_free_from_paddock_message_hpp
#define core_exchange_mount_free_from_paddock_message_hpp

namespace network
{
    struct exchange_mount_free_from_paddock_message : dofus_unit
    {
        std::string name;
        int16_t world_x;
        int16_t world_y;
        std::string liberator;
        
        int16_t id() const override
        { return 6055; } 
        
        exchange_mount_free_from_paddock_message(const std::string & name, const int16_t & world_x, const int16_t & world_y, const std::string & liberator)
        {
            _data << name;
            _data << world_x;
            _data << world_y;
            _data << liberator;
        }
        
        exchange_mount_free_from_paddock_message(byte_buffer & data)
        {
            data >> name;
            data >> world_x;
            data >> world_y;
            data >> liberator;
        }
    };
}

#endif
