//  Generated by desperion protocol_builder

#ifndef core_exchange_bid_house_in_list_updated_message_hpp
#define core_exchange_bid_house_in_list_updated_message_hpp

namespace protocol
{
    struct exchange_bid_house_in_list_updated_message : exchange_bid_house_in_list_added_message
    {
        
        int16_t id() const override
        { return 6337; } 
        
        exchange_bid_house_in_list_updated_message(const int32_t & item_u_i_d, const int32_t & obj_generic_id, const int16_t & power_rate, const bool & over_max, const std::vector<object_effect_ptr> & effects, const std::vector<int32_t> & prices) : exchange_bid_house_in_list_added_message { item_u_i_d,obj_generic_id,power_rate,over_max,effects,prices }
        {
        }
        
        exchange_bid_house_in_list_updated_message(byte_buffer & data) : exchange_bid_house_in_list_added_message { data }
        {
        }
    };
}

#endif
