//  Generated by desperion protocol_builder

#ifndef core_exchange_bid_house_item_add_ok_message_hpp
#define core_exchange_bid_house_item_add_ok_message_hpp

namespace protocol
{
    struct exchange_bid_house_item_add_ok_message : dofus_unit
    {
        object_item_to_sell_in_bid_ptr item_info;
        
        int16_t id() const override
        { return 5945; } 
        
        exchange_bid_house_item_add_ok_message(const object_item_to_sell_in_bid_ptr & item_info)
        {
            _data << item_info->buffer();
        }
        
        exchange_bid_house_item_add_ok_message(byte_buffer & data)
        {
            item_info = std::make_unique<object_item_to_sell_in_bid>(data);
        }
    };
}

#endif
