//  Generated by desperion protocol_builder

#ifndef core_exchange_types_exchanger_description_for_user_message_hpp
#define core_exchange_types_exchanger_description_for_user_message_hpp

namespace protocol
{
    struct exchange_types_exchanger_description_for_user_message : dofus_unit
    {
        std::vector<int32_t> type_description;
        
        int16_t id() const override
        { return 5765; } 
        
        exchange_types_exchanger_description_for_user_message(const std::vector<int32_t> & type_description)
        {
            _data << static_cast<int16_t>(type_description.size());
            for (auto && i : type_description)
                _data << i;
        }
        
        exchange_types_exchanger_description_for_user_message(byte_buffer & data)
        {
            int16_t type_description_size;
            data >> type_description_size;
            type_description.resize(type_description_size);
            for (int16_t i = 0; i < type_description_size; ++i)
                data >> type_description[i];
        }
    };
}

#endif
