//  Generated by desperion protocol_builder

#ifndef core_exchange_modified_payment_for_craft_message_hpp
#define core_exchange_modified_payment_for_craft_message_hpp

namespace network
{
    struct exchange_modified_payment_for_craft_message : dofus_unit
    {
        bool only_success;
        object_item_not_in_container_ptr object;
        
        int16_t id() const override
        { return 5832; } 
        
        exchange_modified_payment_for_craft_message(const bool & only_success, const object_item_not_in_container_ptr & object)
        {
            _data << only_success;
            _data << object->buffer();
        }
        
        exchange_modified_payment_for_craft_message(byte_buffer & data)
        {
            data >> only_success;
            object = std::make_unique<object_item_not_in_container>(data);
        }
    };
}

#endif
