//  Generated by desperion protocol_builder

#ifndef core_exchange_start_ok_npc_trade_message_hpp
#define core_exchange_start_ok_npc_trade_message_hpp

namespace protocol
{
    struct exchange_start_ok_npc_trade_message : dofus_unit
    {
        int32_t npc_id;
        
        int16_t id() const override
        { return 5785; } 
        
        exchange_start_ok_npc_trade_message(const int32_t & npc_id)
        {
            _data << npc_id;
        }
        
        exchange_start_ok_npc_trade_message(byte_buffer & data)
        {
            data >> npc_id;
        }
    };
}

#endif
