//  Generated by desperion protocol_builder

#ifndef core_exchange_shop_stock_started_message_hpp
#define core_exchange_shop_stock_started_message_hpp

namespace protocol
{
    struct exchange_shop_stock_started_message : dofus_unit
    {
        std::vector<object_item_to_sell_ptr> objects_infos;
        
        int16_t id() const override
        { return 5910; } 
        
        exchange_shop_stock_started_message(const std::vector<object_item_to_sell_ptr> & objects_infos)
        {
            _data << static_cast<int16_t>(objects_infos.size());
            for (auto && i : objects_infos)
                _data << i->buffer();
        }
        
        exchange_shop_stock_started_message(byte_buffer & data)
        {
            int16_t objects_infos_size;
            data >> objects_infos_size;
            objects_infos.resize(objects_infos_size);
            for (int16_t i = 0; i < objects_infos_size; ++i)
                objects_infos[i] = std::make_unique<object_item_to_sell>(data);
        }
    };
}

#endif
