//  Generated by desperion protocol_builder

#ifndef core_exchange_start_ok_craft_message_hpp
#define core_exchange_start_ok_craft_message_hpp

namespace protocol
{
    struct exchange_start_ok_craft_message : dofus_unit
    {
        
        int16_t id() const override
        { return 5813; } 
        
        exchange_start_ok_craft_message()
        {
        }
        
        exchange_start_ok_craft_message(byte_buffer & data)
        {
        }
    };
}

#endif
