//  Generated by desperion protocol_builder

#ifndef core_exchange_buy_ok_message_hpp
#define core_exchange_buy_ok_message_hpp

namespace protocol
{
    struct exchange_buy_ok_message : dofus_unit
    {
        
        int16_t id() const override
        { return 5759; } 
        
        exchange_buy_ok_message()
        {
        }
        
        exchange_buy_ok_message(byte_buffer & data)
        {
        }
    };
}

#endif
