//  Generated by desperion protocol_builder

#ifndef core_exchange_shop_stock_movement_removed_message_hpp
#define core_exchange_shop_stock_movement_removed_message_hpp

namespace protocol
{
    struct exchange_shop_stock_movement_removed_message : dofus_unit
    {
        int32_t object_id;
        
        int16_t id() const override
        { return 5907; } 
        
        exchange_shop_stock_movement_removed_message(const int32_t & object_id)
        {
            _data << object_id;
        }
        
        exchange_shop_stock_movement_removed_message(byte_buffer & data)
        {
            data >> object_id;
        }
    };
}

#endif
