//  Generated by desperion protocol_builder

#ifndef core_exchange_start_ok_craft_with_information_message_hpp
#define core_exchange_start_ok_craft_with_information_message_hpp

namespace network
{
    struct exchange_start_ok_craft_with_information_message : exchange_start_ok_craft_message
    {
        int8_t nb_case;
        int32_t skill_id;
        
        int16_t id() const override
        { return 5941; } 
        
        exchange_start_ok_craft_with_information_message(const int8_t & nb_case, const int32_t & skill_id)
        {
            _data << nb_case;
            _data << skill_id;
        }
        
        exchange_start_ok_craft_with_information_message(byte_buffer & data) : exchange_start_ok_craft_message { data }
        {
            data >> nb_case;
            data >> skill_id;
        }
    };
}

#endif
