//  Generated by desperion protocol_builder

#ifndef core_item_no_more_available_message_hpp
#define core_item_no_more_available_message_hpp

namespace protocol
{
    struct item_no_more_available_message : dofus_unit
    {
        
        int16_t id() const override
        { return 5769; } 
        
        item_no_more_available_message()
        {
        }
        
        item_no_more_available_message(byte_buffer & data)
        {
        }
    };
}

#endif
