//  Generated by desperion protocol_builder

#ifndef core_character_level_up_information_message_hpp
#define core_character_level_up_information_message_hpp

namespace network
{
    struct character_level_up_information_message : character_level_up_message
    {
        std::string name;
        int32_t id;
        
        int16_t id() const override
        { return 6076; } 
        
        character_level_up_information_message(const int8_t & new_level, const std::string & name, const int32_t & id) : character_level_up_message { new_level }
        {
            _data << name;
            _data << id;
        }
        
        character_level_up_information_message(byte_buffer & data) : character_level_up_message { data }
        {
            data >> name;
            data >> id;
        }
    };
}

#endif
