//  Generated by desperion protocol_builder

#ifndef core_game_role_play_spell_anim_message_hpp
#define core_game_role_play_spell_anim_message_hpp

namespace network
{
    struct game_role_play_spell_anim_message : dofus_unit
    {
        int32_t caster_id;
        int16_t target_cell_id;
        int16_t spell_id;
        int8_t spell_level;
        
        int16_t id() const override
        { return 6114; } 
        
        game_role_play_spell_anim_message(const int32_t & caster_id, const int16_t & target_cell_id, const int16_t & spell_id, const int8_t & spell_level)
        {
            _data << caster_id;
            _data << target_cell_id;
            _data << spell_id;
            _data << spell_level;
        }
        
        game_role_play_spell_anim_message(byte_buffer & data)
        {
            data >> caster_id;
            data >> target_cell_id;
            data >> spell_id;
            data >> spell_level;
        }
    };
}

#endif
