//  Generated by desperion protocol_builder

#ifndef core_aggressable_status_enum_hpp
#define core_aggressable_status_enum_hpp

namespace network
{
    enum aggressable_status
    {
        NON_AGGRESSABLE = 0,
        PvP_ENABLED_AGGRESSABLE = 10,
        PvP_ENABLED_NON_AGGRESSABLE = 11,
        AvA_ENABLED_AGGRESSABLE = 20,
        AvA_ENABLED_NON_AGGRESSABLE = 21,
        AvA_DISQUALIFIED = 22,
        AvA_PREQUALIFIED_AGGRESSABLE = 23,
    };
}

#endif
