//  Generated by desperion protocol_builder

#ifndef core_hardcore_death_state_enum_hpp
#define core_hardcore_death_state_enum_hpp

namespace network
{
    enum hardcore_death_state
    {
        DEATH_STATE_ALIVE = 0,
        DEATH_STATE_DEAD = 1,
        DEATH_STATE_WAITING_CONFIRMATION = 2,
    };
}

#endif
