//  Generated by desperion protocol_builder

#ifndef core_mount_equiped_error_enum_hpp
#define core_mount_equiped_error_enum_hpp

namespace network
{
    enum mount_equiped_error
    {
        UNSET = 0,
        SET = 1,
        RIDING = 2,
    };
}

#endif
