//  Generated by desperion protocol_builder

#ifndef core_pvp_arena_type_enum_hpp
#define core_pvp_arena_type_enum_hpp

namespace network
{
    enum pvp_arena_type
    {
        ARENA_TYPE_3VS3 = 3,
        ARENA_TYPE_5VS5 = 5,
    };
}

#endif
