//  Generated by desperion protocol_builder

#ifndef core_chat_client_private_message_hpp
#define core_chat_client_private_message_hpp

namespace network
{
    struct chat_client_private_message : chat_abstract_client_message
    {
        std::string receiver;
        
        int16_t id() const override
        { return 851; } 
        
        chat_client_private_message(const std::string & content, const std::string & receiver) : chat_abstract_client_message { content }
        {
            _data << receiver;
        }
        
        chat_client_private_message(byte_buffer & data) : chat_abstract_client_message { data }
        {
            data >> receiver;
        }
    };
}

#endif
