//  Generated by desperion protocol_builder

#ifndef core_chat_abstract_server_message_hpp
#define core_chat_abstract_server_message_hpp

namespace network
{
    struct chat_abstract_server_message : dofus_unit
    {
        int8_t channel;
        std::string content;
        int32_t timestamp;
        std::string fingerprint;
        
        int16_t id() const override
        { return 880; } 
        
        chat_abstract_server_message(const int8_t & channel, const std::string & content, const int32_t & timestamp, const std::string & fingerprint)
        {
            _data << channel;
            _data << content;
            _data << timestamp;
            _data << fingerprint;
        }
        
        chat_abstract_server_message(byte_buffer & data)
        {
            data >> channel;
            data >> content;
            data >> timestamp;
            data >> fingerprint;
        }
    };
}

#endif
