//  Generated by desperion protocol_builder

#ifndef core_abstract_game_action_fight_targeted_ability_message_hpp
#define core_abstract_game_action_fight_targeted_ability_message_hpp

namespace protocol
{
    struct abstract_game_action_fight_targeted_ability_message : abstract_game_action_message
    {
        int32_t target_id;
        int16_t destination_cell_id;
        int8_t critical;
        bool silent_cast;
        
        int16_t id() const override
        { return 6118; } 
        
        abstract_game_action_fight_targeted_ability_message(const int16_t & action_id, const int32_t & source_id, const int32_t & target_id, const int16_t & destination_cell_id, const int8_t & critical, const bool & silent_cast) : abstract_game_action_message { action_id,source_id }
        {
            _data << target_id;
            _data << destination_cell_id;
            _data << critical;
            _data << silent_cast;
        }
        
        abstract_game_action_fight_targeted_ability_message(byte_buffer & data) : abstract_game_action_message { data }
        {
            data >> target_id;
            data >> destination_cell_id;
            data >> critical;
            data >> silent_cast;
        }
    };
}

#endif
