//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_no_spell_cast_message_hpp
#define core_game_action_fight_no_spell_cast_message_hpp

namespace protocol
{
    struct game_action_fight_no_spell_cast_message : dofus_unit
    {
        int32_t spell_level_id;
        
        int16_t id() const override
        { return 6132; } 
        
        game_action_fight_no_spell_cast_message(const int32_t & spell_level_id)
        {
            _data << spell_level_id;
        }
        
        game_action_fight_no_spell_cast_message(byte_buffer & data)
        {
            data >> spell_level_id;
        }
    };
}

#endif
