//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_summon_message_hpp
#define core_game_action_fight_summon_message_hpp

namespace network
{
    struct game_action_fight_summon_message : abstract_game_action_message
    {
        game_fight_fighter_informations_ptr summon;
        
        int16_t id() const override
        { return 5825; } 
        
        game_action_fight_summon_message(const int16_t & action_id, const int32_t & source_id, const game_fight_fighter_informations_ptr & summon) : abstract_game_action_message { action_id,source_id }
        {
            _data << summon->id() << summon->buffer();
        }
        
        game_action_fight_summon_message(byte_buffer & data) : abstract_game_action_message { data }
        {
            int16_t summon_id;
            data >> summon_id;
            summon.reset(type_manager::get_game_fight_fighter_informations(summon_id, data));
        }
    };
}

#endif
