//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_dispell_effect_message_hpp
#define core_game_action_fight_dispell_effect_message_hpp

namespace network
{
    struct game_action_fight_dispell_effect_message : game_action_fight_dispell_message
    {
        int32_t boost_u_i_d;
        
        int16_t id() const override
        { return 6113; } 
        
        game_action_fight_dispell_effect_message(const int32_t & target_id, const int16_t & action_id, const int32_t & source_id, const int32_t & boost_u_i_d) : game_action_fight_dispell_message { target_id,action_id,source_id }
        {
            _data << boost_u_i_d;
        }
        
        game_action_fight_dispell_effect_message(byte_buffer & data) : game_action_fight_dispell_message { data }
        {
            data >> boost_u_i_d;
        }
    };
}

#endif
