//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_dispellable_effect_message_hpp
#define core_game_action_fight_dispellable_effect_message_hpp

namespace network
{
    struct game_action_fight_dispellable_effect_message : abstract_game_action_message
    {
        abstract_fight_dispellable_effect_ptr effect;
        
        int16_t id() const override
        { return 6070; } 
        
        game_action_fight_dispellable_effect_message(const int16_t & action_id, const int32_t & source_id, const abstract_fight_dispellable_effect_ptr & effect) : abstract_game_action_message { action_id,source_id }
        {
            _data << effect->id() << effect->buffer();
        }
        
        game_action_fight_dispellable_effect_message(byte_buffer & data) : abstract_game_action_message { data }
        {
            int16_t effect_id;
            data >> effect_id;
            effect.reset(type_manager::get_abstract_fight_dispellable_effect(effect_id, data));
        }
    };
}

#endif
