//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_close_combat_message_hpp
#define core_game_action_fight_close_combat_message_hpp

namespace network
{
    struct game_action_fight_close_combat_message : abstract_game_action_fight_targeted_ability_message
    {
        int32_t weapon_generic_id;
        
        int16_t id() const override
        { return 6116; } 
        
        game_action_fight_close_combat_message(const int32_t & target_id, const int16_t & destination_cell_id, const int8_t & critical, const bool & silent_cast, const int16_t & action_id, const int32_t & source_id, const int32_t & weapon_generic_id) : abstract_game_action_fight_targeted_ability_message { target_id,destination_cell_id,critical,silent_cast,action_id,source_id }
        {
            _data << weapon_generic_id;
        }
        
        game_action_fight_close_combat_message(byte_buffer & data) : abstract_game_action_fight_targeted_ability_message { data }
        {
            data >> weapon_generic_id;
        }
    };
}

#endif
