//  Generated by desperion protocol_builder

#ifndef core_game_action_fight_life_points_lost_message_hpp
#define core_game_action_fight_life_points_lost_message_hpp

namespace protocol
{
    struct game_action_fight_life_points_lost_message : abstract_game_action_message
    {
        int32_t target_id;
        int16_t loss;
        int16_t permanent_damages;
        
        int16_t id() const override
        { return 6312; } 
        
        game_action_fight_life_points_lost_message(const int16_t & action_id, const int32_t & source_id, const int32_t & target_id, const int16_t & loss, const int16_t & permanent_damages) : abstract_game_action_message { action_id,source_id }
        {
            _data << target_id;
            _data << loss;
            _data << permanent_damages;
        }
        
        game_action_fight_life_points_lost_message(byte_buffer & data) : abstract_game_action_message { data }
        {
            data >> target_id;
            data >> loss;
            data >> permanent_damages;
        }
    };
}

#endif
