//  Generated by desperion protocol_builder

#ifndef core_character_report_message_hpp
#define core_character_report_message_hpp

namespace network
{
    struct character_report_message : dofus_unit
    {
        unsigned_int_ptr reported_id;
        int8_t reason;
        
        int16_t id() const override
        { return 6079; } 
        
        character_report_message(const unsigned_int_ptr & reported_id, const int8_t & reason)
        {
            _data << reported_id->buffer();
            _data << reason;
        }
        
        character_report_message(byte_buffer & data)
        {
            reported_id = std::make_unique<unsigned_int>(data);
            data >> reason;
        }
    };
}

#endif
