//  Generated by desperion protocol_builder

#ifndef core_display_numerical_value_with_age_bonus_message_hpp
#define core_display_numerical_value_with_age_bonus_message_hpp

namespace network
{
    struct display_numerical_value_with_age_bonus_message : display_numerical_value_message
    {
        int32_t value_of_bonus;
        
        int16_t id() const override
        { return 6361; } 
        
        display_numerical_value_with_age_bonus_message(const int32_t & entity_id, const int32_t & value, const int8_t & type, const int32_t & value_of_bonus) : display_numerical_value_message { entity_id,value,type }
        {
            _data << value_of_bonus;
        }
        
        display_numerical_value_with_age_bonus_message(byte_buffer & data) : display_numerical_value_message { data }
        {
            data >> value_of_bonus;
        }
    };
}

#endif
